### ISSUE TITLE
[bal-icon] download icon

### ISSUE THREAD

**Issue by mkasparsone** [baloise-incubator/design-system#1004]
## Summary

Could `balIconDownload` also be added to this list - [design-system-components/p-92b19871.js](https://cdn.jsdelivr.net/npm/@baloise/design-system-components@v12.1.0/dist/design-system-components/p-92b19871.js) so that it would be easily accessible

**Comment by hirsch88** [comment]
Hi @mkasparsone, unfortunately this is not possible otherwise we increase the payload for everybody. Please configure the icons during the initial phase of the Design System.

Moreover, CDN usage is not recommended for production solutions.

**Comment by hirsch88** [comment]
```javascript
import { balIconAccount } from '@baloise/design-system-icons'
import { initialize } from '@baloise/design-system-components'

initialize({ icons: {
   balIconDownload,
} })

```
