### ISSUE TITLE
BalSelect Input value resets when options list is changed

### ISSUE THREAD

**Issue by ManojlovicMilos** [baloise-incubator/design-system#1011]
## BalSelect Input value resets when options list is changed

When list of options changes, bal-select input is set back to empty.

## Steps to reproduce the issue

1. Have a list of options that change depending on the bal-select input.
2. Type something that changes the list.
3. Observe bal-select value reverting to empty.

## Additional information

Example: https://github.com/baloise/design-system-examples/tree/bug/issue_1011

**Comment by hirsch88** [comment]
Hi @ManojlovicMilos did you use the prop `remote` ?

**Comment by hirsch88** [comment]
https://stackblitz.com/edit/angular-wcnqtw?file=src%2Fapp%2Fexample.component.ts&file=src%2Fapp%2Fexample.component.html&showSidebar=0

**Comment by ManojlovicMilos** [comment]
Stackblitz has a package version that works when we include it in our project. Guess that was the point of the Stackblitz (the fix). So yeah, we can confirm that it works :D
