### ISSUE TITLE
Option (Input) to not show dropdown and it's options if the bal-select input is empty.

### ISSUE THREAD

**Issue by ManojlovicMilos** [baloise-incubator/design-system#1012]
### Summary

What I'm discussing here is just a development change.
We need an option to not show dropdown and it's options if the bal-select input is empty.

### Justification

We are using it to show the list of nationalities, and there are many of them.
In order not to fill the DOM with unnecessary options, we need to show them only when user typed in something.

### Must-have functionality

An Input with name which clearly states that dropdown will not be shown if input is empty.
Actual functionality.

### Specific timeline issues / requests

Semi-related issue: https://github.com/baloise-incubator/design-system/issues/1011
I've tried finding a workaround by doing what's given in the example here. This issue prevents it from worki

**Comment by hirsch88** [comment]
Hi @ManojlovicMilos did you use the prop `remote` ?
