### ISSUE TITLE
Modal scrolls page to top

### ISSUE THREAD

**Issue by FilipMarkovski** [baloise-incubator/design-system#1013]
## Detailed description

> Describe in detail the issue you're having.

This happens when you have a page that's not 100vh, but longer than that (imagine a landing page, where you have to scroll down to see the all of the content). We have a case when we click to open a modal and the page in the background scrolls to the top. In the <body> element JS dynamically sets `position: fixed` and `top: 0` (and 2 additional properties, but they don't matter in this case).

> What did you expect to happen? What happened instead? What would you like to see changed?

We have multiple buttons for opening a modal, which are not at the top of the page, that's why for each button click the user gets sent back to the top of the page. If the buttons were at the top of the page, we wouldn't notice this at all.

We expected that the modal will just pop-up on the page without affecting the users journey in the page itself.

> What browser are you working in?

Chrome

## Steps to reproduce the issue

1. Have a page that's longer than the viewport (i.e. landing page, page with enough content that you have to scroll down and reach a section where there is an action button for opening a modal)
2. Click on the action button to open the modal and you'll see that the page will scroll up
3. If  you go to dev tools, you'll see in the console that JS dynamically sets the body of the page to `scroll-behavior: auto; position: fixed; width: 100%; top: 0px; ` when you open the modal.

**Comment by hirsch88** [comment]
will be taken care of in #529
