### ISSUE TITLE
The close arrow is not working only on typeahead select field

### ISSUE THREAD

**Issue by aMiladinovic** [baloise-incubator/design-system#1018]
## Detailed description

> When the dropdown is opened, nothing is selected but you want to close the dropdown on the arrow, it is not closed. It can just be closed with clicking outside of the dropdown.

>When you click on the arrow it should close the option list.

> The browser is Chrome

**Comment by hirsch88** [comment]
Hi @aMiladinovic I tested the issue on chrome with version 12.2.0 and it works.
Only typeahead does not work
