### ISSUE TITLE
[bal-input-slider] dark green bar is not filled to the center of the circle, when moving to the right or left side

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#1037]
![slider-high](https://user-images.githubusercontent.com/17945926/210730232-d1b4be73-4ca0-4fa1-877d-004d6bf34919.png)
![slider-less](https://user-images.githubusercontent.com/17945926/210730240-d8fd6eaf-98bb-470f-a291-50d608ec797d.png)

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/724
