### ISSUE TITLE
[bal-icon] location icon white not working

### ISSUE THREAD

**Issue by GinaBiondo** [baloise-incubator/design-system#1038]
## The location icon is currently not displayed in white

> the icon stays blue if the color is set to white

<img width="42" alt="Bildschirm­foto 2023-01-05 um 09 57 50" src="https://user-images.githubusercontent.com/72393447/210743530-2f2088cc-dc56-4f6b-8881-3b9fb53ce765.png">

**Comment by hirsch88** [comment]
remove the inline styles of the icon
