### ISSUE TITLE
[Modal] Does it work for Safari <= 13

### ISSUE THREAD

**Issue by yannickholzenkamp** [baloise-incubator/design-system#1039]
We had an issue in MyBaloise Private with a modal that was displayed at the very beginning of the application.
In Safari version <= 13 the modal was not displayed because height/width was zero.

Is this a general issue in the Design-System?

Please test with an application that has no components/pages besides the modal that is opened at the beginning.

**Comment by yannickholzenkamp** [comment]
@hirsch88 fyi: issue created

**Comment by hirsch88** [comment]
Hi @yannickholzenkamp I tested the modal with Safari 13 and it worked. let us test that together with your app
