### ISSUE TITLE
[bal-tabs] tab link not working on mobile select

### ISSUE THREAD

**Issue by fabio-tedesco** [baloise-incubator/design-system#1043]
## Detailed description

> when a tab item is a link and the prop selectOnMobile is set to True it doesn't work as expected

## Steps to reproduce the issue

1. mobile view
2. selectOnMobile true
3. tab item is a link
4. link from select doesn't work

**Comment by hirsch88** [comment]
https://baloise-design-system.vercel.app/?path=/story/components-tabs--basic&args=selectOnMobile:true
