### ISSUE TITLE
[bal-list] link highlight design/style missing

### ISSUE THREAD

**Issue by fabio-tedesco** [baloise-incubator/design-system#1044]
## Detailed description

> for online training chapter we'd need an highlighted link
> We'd need an example design for it here https://www.figma.com/file/FVkAs6sb8eBO18qmoXk7YX/%F0%9F%A4%B9%F0%9F%8F%BC%E2%80%8D%E2%99%82%EF%B8%8F-Baloise-Rebranding-Design-Kit?node-id=7975%3A189688&t=bypdynehsYiyaRbe-0 

> the feature should be then implemented in ds

## Additional information

- I will assign it to design first

**Comment by hirsch88** [comment]
@Gagne87 check the use case with application owner magnolia

**Comment by Gagne87** [comment]
Talked with Simone about that topic. We should not follow this.

**Comment by fabio-tedesco** [comment]
Thanks @Gagne87 I will inform QA on our side in order to ignore it
