### ISSUE TITLE
Spacing radio button to validation message

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#1059]
The current spacing of radio buttons to the validation messages is not harmonised with the rest of the layout. Maybe this results in a visually unpleasant experience for users. I propose to harmonize the spacing of the radio buttons to the validation messages with the surrounding elements to achieve a more coherent design.
 
What is your opinion here?

Screenshots:

from application
![image-2023-01-12-11-20-24-323](https://user-images.githubusercontent.com/292344/212278303-b96c37ec-a954-4496-9069-40dd291f9e3a.png)

from example app repository (branch 1059/gap_radio_validation)
![SCREEENSHOT](https://user-images.githubusercontent.com/292344/212307773-fcfca6e4-6c4d-49ba-ba56-e2452eb081a6.png)

Severity:
Minor

**Comment by hirsch88** [comment]
@tklueber every form-control is 48px height so that it is accessible for mobile users

was designed like that
