### ISSUE TITLE
[Figma] Onboarding documentation

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#1060]
We would like to provide a documentation about how to set up a structure in Figma. Contents should be according to the Figma file linked to this ticket. 

[Figma](https://www.figma.com/file/CWbj6tAqdWkpkRHEgle5V5/Structure?node-id=1436%3A3330&t=mF8T80D9kiiPvUAF-0)

**Comment by clastzoo** [comment]
@Gagne87 any feedback needed from my side? Are you checking the open points with Seamus?

**Comment by clastzoo** [comment]
💡 Inupt : Shall we adapt the layout to 1920 x 1080 to create a slidedeck which we could share as a starting point? Sen't you a Slack message about it

**Comment by hirsch88** [comment]
waiting for feedback

**Comment by clastzoo** [comment]
@hirsch88 @Gagne87 how can i help / what can i review?
