### ISSUE TITLE
DS 12.4.0: Angular app cannot start anymore

### ISSUE THREAD

**Issue by svene** [baloise-incubator/design-system#1061]
## Detailed description

After upgrading from DS 12.3.0 to DS 12.4.0 our angular app has a compile error during startup and therefore is not functional.
Here is the error message as screen dump:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/51710/212316671-09c1f9fb-4757-4724-9c88-e0c9aade247c.png)

> What did you expect to happen? What happened instead? What would you like to see changed?

Application starting and working without errors

> What browser are you working in?

chrome

## Steps to reproduce the issue

Let me know in case you need an example-app branch to verify this problem.

**Comment by hirsch88** [comment]
@svene fixed with 12.4.1

**Comment by svene** [comment]
Thanks for the quick fix !
