### ISSUE TITLE
[Figma] Adapt Notifications from DS

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#1070]
There was a hint from Belgium (Stefaan communicated it) that we don't have the Notifications in our Figma Library.

https://baloise-design-system.vercel.app/?path=/docs/components-notification--basic

![Image](https://user-images.githubusercontent.com/62377419/212965347-aaa4560e-03e9-44f2-8a29-4ed1b744dc2c.png)

**Comment by clastzoo** [comment]
Can we combine it with the toast?

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/796
