### ISSUE TITLE
[Figma] File Review

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#1072]
Acceptance Criteria (TO BE EXPANDED)

- [ ] Cover is set
- [ ] File/Pages are structured
- [ ] Documentation is written, examples are provided (Think about real content)
- [ ] Component Naming and Description + Link is availble
- [ ] Styles are set on component / style level,  styles are updated
- [ ] Latest state is published
- [ ] File is compared to DS and approved/discussed with a developer

### Prio 1 Set
- [ ] Typography
- [ ] Colors
- [ ] Grid
- [ ] Iconography
- [ ] Components
- [ ] Spacing

### Prio 2 Set
- [ ] Helpers
- [ ] Brand Assets

Open Question / Input Inspiration 
xx

- Deep Level Analysis of our Figma Components (https://medium.com/eightshapes-llc/the-figma-component-review-f42114450b4d)

![Image](https://user-images.githubusercontent.com/62377419/213197423-b15a793a-0b0e-4b0a-94e4-120f465e9795.png)

- https://www.designsystemchecklist.com/
- Get Started File in Design System or Country Project folder?

**Comment by clastzoo** [comment]
@Gagne87 TBD tomorrow in the daily – may you have some additional ideas, please feel free to adjust the ticket. 

Might make sense to create a file for each file?

**Comment by clastzoo** [comment]
TBD on Monday

- h5 topic 
- icons size

![Image](https://user-images.githubusercontent.com/62377419/213672383-b332bbe3-4524-4e5f-a2b9-8f43e2225ecf.png)
![Image](https://user-images.githubusercontent.com/62377419/213672382-c08eaf21-e670-42e8-b84e-6a0412a56706.png)
![Image](https://user-images.githubusercontent.com/62377419/213672384-876a8ed9-7e5b-4733-ae3f-4f2e715c1d4b.png)

**Comment by clastzoo** [comment]
-

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/801
