### ISSUE TITLE
[bal-number-input] "max" & "min" props not working

### ISSUE THREAD

**Issue by JasperDeLanghe** [baloise-incubator/design-system#1079]
## Detailed description

> Describe in detail the issue you're having.

Setting a `max` and/or `min` prop on the `bal-number-input` does not seem to enforce these boundaries.

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected the number input to get an `invalid` state, or just not being able to enter a higher/lower number.
Instead there's no visual feedback the input is invalid.

## Steps to reproduce the issue

1. Set the `max` prop equal to `15` on the component
2. Enter `16` in the input

## Side question about the `bal-number-input`

Is there a way to disable the formatting?
We are using the component for housenumbers, where we'd like to max it out to 4 digits.
Entering for example `1014` formats it to `1 014`, but we'd like to keep it as `1014` in this case.

**Comment by mladenplaninicic** [comment]
@JasperDeLanghe we don't do validation, we just pass min and max to the native input element

**Comment by ThomasSeyssensTPO** [comment]
@mladenplaninicic Shouldn't the component check the min & max values too? Why would you have the props if the input is not keeping record of them? The props are useless this way.
