### ISSUE TITLE
option to hide metanavigation link

### ISSUE THREAD

**Issue by janineKleessen** [baloise-incubator/design-system#1132]
On  https://www.baloise.com/de/home.html is only one homepage available. 
So it should be possible to hide this link in the metanav.
We can not hide it by oureself because we need the informations in bal-navigation-level-meta> -> label/mobilelabel and link for the rendering of the mobilenavigation.
Can you provide a property to hide the desktopLink?

**Comment by hirsch88** [comment]
@janineKleessen So can we say always when in the Meta Navigation there is only one link on Desktop we can hide them?

**Comment by janineKleessen** [comment]
@hirsch88 I'm not sure about that, because you can add a list of items and than you can only add one without the own homepage. This should be a desicion by Babs.

**Comment by hirsch88** [comment]
Will be done with the refactoring
