### ISSUE TITLE
Define one with for forms = is-compact instead of is-detail-page

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#1140]
- [ ] check other ui libs what they use for the max-width
- [ ] goal is the have one container for forms

**Comment by Gagne87** [comment]
The consent I found by doing a little bit of research is to use a container-width for cards/forms on desktop of around 700px. I prepared a couple of examples here: https://www.figma.com/file/lgDn2QZqoJJlYzGTe6cOmr/%F0%9F%A7%A9-Components?node-id=9045%3A89548
Let's discuss.

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/800
