### ISSUE TITLE
Add Vertical Stepper

### ISSUE THREAD

**Issue by StefaanSaeys** [baloise-incubator/design-system#1155]
Nowadays, only horizontal steppers are added to the design system. For some of our applications, a vertical stepper is desired. 

We made a proposal on following page : https://www.figma.com/file/zbWJfrdgKNdXWb0x3DD2VK/Figma-Corrections-Group-Design-System?node-id=9%3A92&t=XRhoprQYGdTtX2l8-0

We also did some suggestions for improvement. 

Clarify if you are asking for both design and development, or just design, or just development.

Design / development

Provide the business reasons for this request.

we need this vertical stepper in our process orchestration tool

Describe the full user experience for this feature. Also define the metrics by which we can measure success/failure for the user.

### Must-have functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Baloise Desing System team will work with you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an upcoming release?

_NB: The Baloise Desing System team will try to work with your timeline, but it's not guaranteed. The earlier you make a request in advance of a desired delivery date, the better!_

### Available extra resources
as fast as possible concerning design. 

What resources do you have to assist this effort?

_Baloise Desing System is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/691
