### ISSUE TITLE
[Figma Refactoring] Align Background Color

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#1157]
I noticed following styling issue: We use _different_ background color for the same purpose, e.g. for "warning": 

- **Tag:** warning-5
- **Toast:** warning-2
- **Notification:** warning-2
- **Snackbar:** warning-2
- **Badge:** color-warning
- **Button:** warning-1 / **hover:** warning-5

We should align the background color for above mentioned components. 

**Note:** This is just an example, the color has to be aligned for most of the backgrounds.

**Comment by hirsch88** [comment]
![Image](https://user-images.githubusercontent.com/6384499/221789506-98d37d84-c52a-46a8-b2b8-34009361cb2a.png)
