### ISSUE TITLE
BalIcon does not render all icons anymore

### ISSUE THREAD

**Issue by ThomasSeyssensTPO** [baloise-incubator/design-system#1159]
## Detailed description

When using BalIcon, some of the icons do not render. The SVG is not added in the HTML, so it looks like the component is not able to get the icon by name.

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

## Steps to reproduce the issue

1. Use BalIcon and use the account icon in the name prop

**Comment by alexsoeres** [comment]
For me it's the same with Angular 15 and Design System 12.7.1

**Comment by ThomasSeyssensTPO** [comment]
Bug is already fixed. Seemed like it was a config issue, forgot to add the icons in the configuration.
https://baloise-design-system.vercel.app/?path=/docs/development-migration-migration-11-x-to-12-x--page&globals=framework:react
