### ISSUE TITLE
[Bug] Hyphen is missing again in the product slider iOS specific

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#1163]
![Image](https://user-images.githubusercontent.com/62377419/220856011-4aba3c4d-7109-4e0c-9495-05ad355547dd.png)

Seems to be a specific iOS issue, appears only on Mac and IPhone.

Iphone
- Chrome
- Safari 
- Firefox
- Edge

Mac
- Safari

**Comment by Gagne87** [comment]
@clastzoo please add browser details.

**Comment by mladenplaninicic** [comment]
@clastzoo it works in Safari version 16.3. Also works on mobile, versions 15.2 and 16.2 (tried on simulators). 

On which version exactly you tested?

![Image](https://user-images.githubusercontent.com/28272339/221211666-f6dd3a15-6e13-4515-9829-b5d3a0f24caf.png)

**Comment by mladenplaninicic** [comment]
Issue is on mobile device, and i guess on mac version 15.
