### ISSUE TITLE
Accordion (bal-accordion): add-on option for lightweight presentation

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#1170]
We are looking to update the visual presentation of the existing Accordion component. The current component expands its content with a large button at the bottom. 
![image](https://user-images.githubusercontent.com/292344/221202262-411cd314-b60d-493a-b704-1f4ef6a78371.png)

We would like to place an order to change this into a small triangle on the right-hand side of the component that users can click to expand the content. The visual presentation should be customizable by using parameters, the behaviour of the components should remain the same.
We know that it is already possible to define text and icon depending on the state. What is not possible without "CSS" tricks is to adjust and position the button to expand and collapse in the mapped way.
![image](https://user-images.githubusercontent.com/292344/221200820-2e00d3c1-9770-4d97-b336-bdefd81f4c63.png)

We have already received positive feedback during a UX discussion in Art KK regarding the proposed new design. The updated visual presentation is expected to be more aesthetically pleasing, user-friendly, and lightweight. We plan to implement this component in multiple areas of our applications, and we know that other websites have similar visualizations that we want to use as a reference.

To give you an idea of the use for which we need it, I would like to show you a mock-up for the upcoming Offeringspage.
![image](https://user-images.githubusercontent.com/292344/221201511-b35d4f2f-32e7-4dc0-afa8-900b2be3c1f2.png)

If you have any questions (technical or ux/design related) please ask me directly.

Thanks in advance

**Comment by hirsch88** [comment]
Release with version 12.12.0

https://github.com/baloise/design-system/blob/main/packages/components/CHANGELOG.md
