### ISSUE TITLE
[Clean-Up] Application Header Figma

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#1171]
There are currently several applications within different projects around baloise.

We have to choose one and adjust to the technical ds. 

![Image](https://user-images.githubusercontent.com/62377419/221218758-8ccf1671-6663-4bfc-b874-f8b9125bddf6.png)

**Comment by hirsch88** [comment]
@clastzoo checkout our component navbar

https://baloise-design-system.vercel.app/?path=/docs/components-navbar--basic
