### ISSUE TITLE
[bal-carousel] - basic carousel with controls large transform the items not completly

### ISSUE THREAD

**Issue by Sw0rdiX** [baloise-incubator/design-system#1175]
The Basic Carousel with combination of Navigation "Large" causes not nice transforming.

On all Viewports the transformation is not full one item it calculations less and this leads to cutted logos at the end.

See videos : 

desktop
https://user-images.githubusercontent.com/3681337/221572649-5f46ee10-0d49-4efa-b9d3-3a851e03387d.mov

tablet
https://user-images.githubusercontent.com/3681337/221572662-dd5b057c-a971-46a9-9e68-1bc17ceb5bf3.mov

mobile
https://user-images.githubusercontent.com/3681337/221572675-ff525b49-0285-477f-bc4e-2678f930ccea.mov

**Comment by hirsch88** [comment]
done with version 12.8.0

https://github.com/baloise-incubator/design-system/blob/next/packages/components/CHANGELOG.md#1280
