### ISSUE TITLE
contactjs cannot resolve

### ISSUE THREAD

**Issue by Sw0rdiX** [baloise-incubator/design-system#1180]
[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'contactjs' is imported by ./node_modules/@baloise/design-system-components/dist/collection/utils/swipe.js,
           but could not be resolved – treating it as an external dependency

<img width="789" alt="image" src="https://user-images.githubusercontent.com/3681337/221679558-66d3567d-8cda-40dd-9dd9-51211a171845.png">

i added the contactjs to my dependencies in package.json to resolve the problem.
the same issue we had after DS Team added hammerjs. 

edit found issue : https://github.com/baloise-incubator/design-system/pull/801

**Comment by hirsch88** [comment]
@mladenplaninicic remove contactjs in the root package.json and add it to the dependencies in the packages/components
