### ISSUE TITLE
[Grid] Double check grids with technical DS

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#1197]
VPL -  Full HD - 1920 → .... // 12c - col-widht **80**, gutter **40**
VPL - Max Widescreen - 1408 ↔ 1920 //  12c - col-widht **auto**, gutter **24**, margin **120**
VPL - High Definition - 1216 ↔ 1407 // 12c - col-widht **auto**, gutter **32**, margin **48**
VPL - Min - 1024 ↔ 1215 //  12c - col-widht **auto**, gutter **32**, margin **48**

VPM - Min - 769 ↔ 1023 //  12c - col-widht **auto**, gutter **16**, margin **48**

VPS - Min - 375 ↔ 768 // 12c - col-widht **auto**, gutter **8**, margin **16**

**Comment by clastzoo** [comment]
TBD Who's gonna support :)

**Comment by hirsch88** [comment]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/6384499/223054359-e0d52869-2382-49f7-9671-a7c4958d019c.png">

https://baloise-design-system.vercel.app/?path=/docs/foundation-grid-overview--page

**Comment by hirsch88** [comment]
- High-Definition and Widescreen are wrong in FIGMA

**Comment by hirsch88** [comment]
Hi @clastzoo 

@Gagne87 and I adjusted FIGMA to the technical docs
