### ISSUE TITLE
fix(number-input): check decimal symbol

### ISSUE THREAD

**Issue by StefaanSaeys** [baloise-incubator/design-system#1217]
Use this template if you want to request a breaking change an existing feature.

### Summary

In het numeric data input field the '.' from your numeric keyboard doesn't react as a ','; so where people have to input eg price of their car we show 1800025 euro instead of the 18000,25 euro. Isn't it possible to change the behaviour of the numeric . to a comma seperator in this input field?

> 

#### What is the current proplem to solve?

People input their prices with numeric keyboards as they are used on several sites. They don't review the prices en so we make quotes based on wrong prices (x100).

**Comment by hirsch88** [comment]
- [ ] enable dots for input too, but change it to the regions default
