### ISSUE TITLE
Button component Figma improvements

### ISSUE THREAD

**Issue by StefaanSaeys** [baloise-incubator/design-system#1237]
Dries made some improvement to the button component in Figma. 

You can consult the details here: https://www.figma.com/file/zbWJfrdgKNdXWb0x3DD2VK/branch/oPldc2jfgXOCWWAQs5FHZa/Figma-Corrections-Group-Design-System?node-id=120-2848&t=2IVlK24Os31gyCCG-0

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/799
