### ISSUE TITLE
Navigation with Tab-Key doesn't work (mostly in Firefox)

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#131]
Expected:

- focus of buttons/links should always be visible

- when the overlay is open, only the content of the overlay should be accessible with tab key

**Comment by hirsch88** [comment]
#879 liked with

**Comment by nobilo** [comment]
BalAutoFocus in modal not working when you open it for second or any other time(works only on first open)

**Comment by hirsch88** [comment]
done with https://github.com/baloise-incubator/design-system/issues/879
