### ISSUE TITLE
Magnolia header and elements overlap tooltip (esp. for mobile)

### ISSUE THREAD

**Issue by svene** [baloise-incubator/design-system#156]
## Detailed description

When we use the app in the mode integrated with Magnolia the Magnolia header overlaps the tooltip.
This is especially visible in the mobile mode where the tooltip is fullscreen.

The reason is that the Magnolia elements have a z-index of 104 and the tooltip has a z-index of 100.

> What did you expect to happen? What happened instead? What would you like to see changed?
In my opinion the tooltip should be visible completely so that the content is not cut.

> What browser are you working in?
Chrome

## Steps to reproduce the issue
Open a tooltip in a Magnolia integrated app in mobile resolution.

## Additional information
I added 3 screenshots:
screenshot 1: shows the cut off text of the tooltip
![2022-07-05_magnolia-overlaps-tooltip](https://user-images.githubusercontent.com/51710/177291522-f7d13087-2f62-425b-b87e-f54fc130e080.png)

screenshot 2: shows z-index of Magnolia elements
![2022-07-05_magnolia-overlaps-tooltip-2](https://user-images.githubusercontent.com/51710/177291641-00e5f7da-cd86-48b2-8c03-4e143dfc99a1.png)

screenshot 3: shows effect of increased z-index (105) of tooltip
![2022-07-05_magnolia-overlaps-tooltip-3](https://user-images.githubusercontent.com/51710/177291654-4df8c843-b409-415d-8c27-567eedd889ef.png)

I am not sure what the best solution would be to tackle this problem.

**Comment by hirsch88** [comment]
25.8 with IBM X and SelfService to test the implementation

**Comment by hirsch88** [comment]
will be solved with the new template
