### ISSUE TITLE
youtube-Videos / Fallback for data privacy handling

### ISSUE THREAD

**Issue by christophgeering** [baloise-incubator/design-system#183]
Fallback design à la OneTrust Coookie banner for Youtube videos approval: 
https://jira.ibmix.de/browse/BARE-165
Again, we save on costs when we supply the design.

- [ ] Implementing design

**Comment by clastzoo** [comment]
Design Draft can be found here:
https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=3658%3A34759 

Needs to be double checked with babs for correct text and functionality.

**Comment by Gagne87** [comment]
Ticket will be closed as basic design has been generated and final design will depend on technical solution.
