### ISSUE TITLE
[bal-datepicker] -  refactor

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#207]
The goal is to use parts of the date-picker separately.

Grid
Month Selection
Year Selection
Date Navigation
Input with the above components
This also increases the testability

Connected issue - [#761](https://github.com/baloise-incubator/design-system/issues/761)
Connected issue - [#975](https://github.com/baloise-incubator/design-system/issues/975)
Connected issue - [#913](https://github.com/baloise-incubator/design-system/issues/913)
Connected issue - [#497](https://github.com/baloise-incubator/design-system/issues/497)

**Due time en of January**

**Comment by hirsch88** [comment]
1. Datepicker without mont and year select
2. Datepicker only input . three inputs or one

**Comment by hirsch88** [comment]
https://ant.design/components/date-picker

**Comment by Gagne87** [comment]
@hirsch88 we should discuss if we still need a datepicker at all before refactoring. As my [market research](https://www.figma.com/file/lgDn2QZqoJJlYzGTe6cOmr/%F0%9F%A7%A9-Components?node-id=1696%3A9575) shows it does not seem best practise to use this pattern at least for birthdates. Let's discuss on Monday how we will proceed. Best after the daily.

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/695
