### ISSUE TITLE
Define global rule for inverted styles

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#228]
### Current State
At the moment, the inverted styles are not defined globaly in Figma. The Technical design system had this feature already implemented, but is not accessible on several backgrounds.

Next Steps:
- [ ] Understand how inverted styles are currently implemented on the technical design system (Tokens?)
- [ ] Find use cases where inverted styles would be helpful
- [ ] Come up with a visual proposal 

### Candidate Components 
- Buttons
- Accordions
- Checkbox
- Radio
- Switch
- Tag

**Comment by Gagne87** [comment]
@clastzoo I would say this one is not important for Go-Live, right? In this case I would move it to the backlog.

**Comment by Gagne87** [comment]
@Gagne87 also check if buttons with our 4 main colors would be desirable.
