### ISSUE TITLE
Focus States on colored backgrounds

### ISSUE THREAD

**Issue by GinaBiondo-aperto** [baloise-incubator/design-system#229]
## Detailed description

the current mixin for the focus states contains a white shadow (border). On colored backgrounds, this looks a bit off.
<img width="379" alt="Bildschirmfoto 2022-07-14 um 09 27 36" src="https://user-images.githubusercontent.com/72393447/178926298-c1a4d825-ed06-41a3-8fb0-2e84db3474e9.png">

Maybe we can add a mixin to be used for elements on colored backgrounds. Maybe something with a transparent border and an outline to achieve the design with rounded corners and spacing.

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/709
