### ISSUE TITLE
Bal Badge responsiveness based on inner content

### ISSUE THREAD

**Issue by nobilo** [baloise-incubator/design-system#240]
## Bal Badge responsiveness based on inner content

When content of badge is bigger like 4 digits, text is not visible.

## Steps to reproduce the issue

1. Try to use bal-badge with 4233 for example
2. 
## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/11984467/179194851-54451681-d4bb-47d6-bd65-af70974ad94f.png)

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/710
