### ISSUE TITLE
bal-icon add a property or possebility to read in svg from a file

### ISSUE THREAD

**Issue by CookieMonster70** [baloise-incubator/design-system#252]
#173 
### Summary

At the moment if you want to use <bal-icon> with svg data, you can add string with svg data to the svg property, but this features makes the html code hard read if you have a string with a length > 200.

### Justification

If you have a large string with SVG data and you use <bal-icon>, the html of the component starts look very overloaded and make it heavy readable.

### Must-have functionality

It would be good that you can use instead of string also the path to assets/icons/xy.svg where the svg data are stored. 

I would prefere something like:

`<bal-icon svgsrc="assets/icon/myIcon.svg"`

As it is at the moment:

`<bal-icon color="primary" size="large" svg="<svg viewBox=" 0 0 30 30" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" clip-rule="evenodd" d="M14.9987 0C6.71662 0 0 6.88563 0 15.3801C0 22.1751 4.29757 27.9391 10.2582 29.9727C11.0086 30.1144 11.2821 29.6395 11.2821 29.2316C11.2821 28.8672 11.2692 27.8994 11.2618 26.6163C7.08952 27.5454 .......... </svg>">
</bal-icon>`

But if you have something like this, it starts to look hardly readable:

`<bal-icon color="primary" size="large" svg="<svg version="1.1"
	 xmlns="http://www.w3.org/2000/svg"
	 x="0px" y="0px" viewBox="0 0 80 80" overflow="visible" enable-background="new 0 0 80 80"
	 id="top-offer-on"
	 xml:space="preserve">
<defs>
</defs>
<polygon fill="#ff9900" points="39.999,5.286 46.335,0 50.727,6.987 58.386,3.916 60.404,11.917 68.637,11.363 68.083,19.596
	76.085,21.614 73.015,29.273 80,33.667 74.712,39.999 80,46.335 73.015,50.728 76.085,58.386 68.083,60.403 68.637,68.637 
	60.404,68.083 58.386,76.085 50.727,73.015 46.335,80 39.999,74.712 33.666,80 29.273,73.015 21.614,76.085 19.596,68.083 
	11.363,68.637 11.917,60.403 3.915,58.386 6.986,50.728 0,46.335 5.286,39.999 0,33.667 6.986,29.273 3.915,21.614 11.917,19.596 
	11.363,11.363 19.596,11.917 21.614,3.916 29.273,6.987 33.666,0 "/>
<path fill="#FFFFFF" d="M27.316,26.931c0.477,0,0.91,0.042,1.302,0.126c0.393,0.084,0.729,0.222,1.009,0.413
	c0.279,0.191,0.496,0.446,0.65,0.763s0.231,0.709,0.231,1.176c0,0.504-0.114,0.924-0.344,1.26c-0.229,0.336-0.566,0.611-1.015,0.826
	c0.616,0.178,1.076,0.488,1.379,0.931c0.304,0.443,0.455,0.978,0.455,1.603c0,0.504-0.098,0.94-0.294,1.309s-0.46,0.67-0.791,0.903
	c-0.331,0.233-0.709,0.406-1.134,0.518s-0.861,0.168-1.31,0.168h-4.844v-9.996H27.316z M27.036,30.977
	c0.393,0,0.714-0.093,0.967-0.28c0.252-0.187,0.378-0.49,0.378-0.91c0-0.233-0.042-0.424-0.126-0.574s-0.196-0.266-0.336-0.35
	.................
</svg>
">
</bal-icon>`

**Comment by joachimprinzbach** [comment]
@CookieMonster70 implemented a pipe as a workaround, you can ask him for the solution.

**Comment by hirsch88** [comment]
@CookieMonster70 you are able to pass the svg attribute with javascript, so that it is never exposed to the DOM
