### ISSUE TITLE
Compile error when integrating design system with angular v10

### ISSUE THREAD

**Issue by joachimprinzbach** [baloise-incubator/design-system#258]

**Comment by nobilo** [comment]
@Winderbueno we support LTS versions from angular, which is currently 12. Pls try to update to this version of angular and to the newest version of the Design system, i have tested it on your project and it seems like it is working, also if you want to check how it works you can always clone our example repo with branch [next](https://github.com/baloise/design-system-examples/tree/next) or  [feat/angular-v12-next](https://github.com/baloise/design-system-examples/tree/feat/angular-v12-next)
