### ISSUE TITLE
[Select] Icon Position and Rotation

### ISSUE THREAD

**Issue by GinaBiondo** [baloise-incubator/design-system#27]
### (different issues in different browsers)

When the dropdown is open the arrow icon is not horizontally centered anymore but shifted downwards a bit:
<img width="638" alt="Bildschirmfoto 2022-04-19 um 14 50 56" src="https://user-images.githubusercontent.com/72393447/164008001-4a3c125b-7677-40c3-b8e0-8f7c9e0b0bca.png">

In Safari/Firefox the Icon is not flipped when the drop down is open:
<img width="650" alt="Bildschirmfoto 2022-04-19 um 14 51 31" src="https://user-images.githubusercontent.com/72393447/164008131-9889798d-be3e-457c-bff8-6130f705efd2.png">

**Comment by hirsch88** [comment]
should be fixed with => https://github.com/baloise-incubator/design-system/pull/394
