### ISSUE TITLE
poor contrast by disabled fields on iphone

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#278]
## Summary
Values in disabled components are very difficult to read on iphone devices.

In other browsers tested, such as Chrome, Firefox and Safari on the Macbook, the contrast is high enough that the values can be read even on disabled fields.

## Relevant information
following screenshots from bdh premium calculator and directly from storybook (all on simulated iphone 12 - but also tested on real device):
![screen1_iphone](https://user-images.githubusercontent.com/292344/181725553-6eb40a99-cc23-4ad6-aa6e-301a1ecf152f.png)
![screen2_iphone](https://user-images.githubusercontent.com/292344/181725570-f3e4f40b-097a-4bec-a79e-e44083d82f3a.png)

....in contrast, the last screenshot is from a android device:
![screen3_android](https://user-images.githubusercontent.com/292344/181725581-1f85f0bd-13a2-49c7-9297-608edcdd799a.jpg)

**Comment by clastzoo** [comment]
Design is done ✅ 

Please implement the following behaviour:

Disabled Field:

Border - `$grey4`
Background - `$grey2`
Text  - `$grey4`
Field Hint - `$grey4`
Icon - `$grey4`

**Comment by hirsch88** [comment]
text is grey-5

**Comment by tklueber** [comment]
[Unfortunately, current tests show that the error still exists. The following screenshots show that "disabled" fields are very difficult to read on iPhone devices.
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-23 at 13 20 27](https://user-images.githubusercontent.com/292344/214038960-2883650e-34fb-4352-b4df-a9052a54905a.png)
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-23 at 13 19 16](https://user-images.githubusercontent.com/292344/214039070-7b26db26-149c-45af-9c76-a5a2a2f391f9.png)
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-23 at 13 18 40](https://user-images.githubusercontent.com/292344/214039110-5dd18a53-758d-42c8-b16a-e7c37e6507d1.png)


That's why I'm opening this issue again.

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/804
