### ISSUE TITLE
Refine concept for job result page

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#286]
According to Nina and Janine the visual concept for the Job Search Component was not properly done and therefore needs a refinement from our side. 

**Current implementation(s):** 

1. https://www.baloise.com/de/DE/jobs/arbeitgeber.html
2. https://www.baloise.com/de/jobs/alle-jobangebote.html?MultiLanguageFilter=allLanguage&displayLimit=10&editMode=false&query-str=

**Design Draft (Meta):** 

- https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=7479%3A173164

**To-do's:**

- [x] Analyze old vs. new concept
- [x] Refine design
- [x] Discuss solution with Janine and Nina

**Comment by clastzoo** [comment]
Design is refined, waiting for Janines feedback.
