### ISSUE TITLE
Adjust bal-close component (add new icon)

### ISSUE THREAD

**Issue by mladenplaninicic** [baloise-incubator/design-system#289]

**Comment by Gagne87** [comment]
#317

**Comment by hirsch88** [comment]
1. use close icon
2. use html button and not the bad-button

**Comment by mladenplaninicic** [comment]
small => icon x-small
default => icon default
medium => icon medium
tag small => close small
tag rest => close defualt
toast and snackbar => close default
modal, popover => close medium
