### ISSUE TITLE
Digital intake (TCS/Baloise)

### ISSUE THREAD

**Issue by christophgeering** [baloise-incubator/design-system#301]
TCS (Touring Club Schweiz, see https://www.tcs.ch/de/kontakt-fragen/notruf-schaden/#anchor_notfall) has launched a new online assistance where you can report your need online and where you directly see who is coming to help you and how long that will take. See: https://online-assistance.tcs.ch/request/request-authentication?lang=de&_gl=1*flcaoh*_ga*MTQ4MjcwNjkyNy4xNjYwMTIwNjk0*_ga_1M63M068CT*MTY2MDEyMDY5My4xLjEuMTY2MDEyMDgwMy4w&_ga=2.230059420.126645953.1660120694-1482706927.1660120694

TCS wants to offer this service also in a Baloise look & feel in October as we are one of their big partners. Therefore they want to implement the forms etc. according to the new branding.

**Comment by christophgeering** [comment]
Accounts have beenn created (thanks @Gagne87). TCS will be informed to contact @christophgeering in case of questions. Right now: no further actions required - waiting for a draft to review

**Comment by clastzoo** [comment]
Design Spec can be found here: 

https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=32354%3A334430

**Comment by joachimprinzbach** [comment]
Waiting for Feedback from TCS
