### ISSUE TITLE
Refinement & preparation next sprint

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#307]
According to Janine the list mentioned below should be focus for our design work before holidays. Following things have to be done: 

- [x] Refine tickets in development (first block of list)
- [x] Refine tickets planned for the next sprint (second block of list)
- [ ] Sync with Janine before vacation

---------------------------------------------------

Themen die gerade noch in Arbeit sind können ja gleich nochmal angeschaut werden, damit wir sie dann final haben.

- [x] MagazinTeaser/ MagzinTeaser Overview / NewsTeaser/Blog Stream [BARE-258](https://jira.ibmix.de/browse/BARE-258)/[BARE-243](https://jira.ibmix.de/browse/BARE-243)
- [x] Imageslider [BARE-286](https://jira.ibmix.de/browse/BARE-286)
- [ ] Produktslider [BARE-215](https://jira.ibmix.de/browse/BARE-215)
- [x] Berater DE Seite [BARE-282](https://jira.ibmix.de/browse/BARE-282)
- [x] Job Seach Component (da war ja das [Baloise.de](http://baloise.de/) Team schon wegen ihrer Webinargeschichte dran) Jobs gehen aktuell wieder [BARE-221](https://jira.ibmix.de/browse/BARE-221)

2. Themen die Aufgrund euere Prio demnächst angefangen werden sollten

~~- [ ] Text/Image Widget [BARE-134](https://jira.ibmix.de/browse/BARE-134) **WRONG COMPONENT - OBSOLETE**~~
~~- [ ] Product Packages Table [BARE-245](https://jira.ibmix.de/browse/BARE-245) **IRRELEVANT CREATED NEW TICKET** : https://github.com/baloise-incubator/design-system/issues/343~~
- [x] Back Teaser [BARE-298](https://jira.ibmix.de/browse/BARE-298)
- [ ] Maps [BARE-260](https://jira.ibmix.de/browse/BARE-260)

**Comment by clastzoo** [comment]
Product Slider – TBD with @Gagne87 & @mladenplaninicic, Solution needs to be delivered by us: [Proposal](https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=28762%3A331060) 

Maps – Still work in progress, highly likeable to be done by the EOB tmrw.
