### ISSUE TITLE
Icon Request - Filter/Funnel Icon

### ISSUE THREAD

**Issue by alexsoeres** [baloise-incubator/design-system#309]
### Summary

I'd like to request a filter icon.

### Justification

I need an Icon for filtering by column and I can't find an appropriate icon for that purpose. A funnel symbol would suit the most.

### Specific timeline issues / requests

It's for an upcoming feature, though it's not urgent

**Comment by Gagne87** [comment]
Hi @alexsoeres, just uploaded an icon to our Frontify (https://brand.baloise.com/screens/4158). Let me know if you cannot access or the icon doesn't suit you. (cc @clastzoo )

**Comment by alexsoeres** [comment]
it's perfect! thanks ^^
