### ISSUE TITLE
Adjust Z-Index Levels of the DS

### ISSUE THREAD

**Issue by GinaBiondo-aperto** [baloise-incubator/design-system#312]
## Z Levels for Navigation and Modal need to be adjusted

<img width="1608" alt="Bildschirmfoto 2022-08-08 um 10 37 27" src="https://user-images.githubusercontent.com/72393447/183376300-0ebfc8a4-68db-4f7f-9771-1848e21eada1.png">

## Detailed description

> Currently the navigation overlaps everything
> modals should be on top of every content if present

Navigation
Modals
Pop Over
Overlays

Idea Playground
https://www.figma.com/file/lgDn2QZqoJJlYzGTe6cOmr/%F0%9F%A7%A9-Components?node-id=7573%3A85688

**Comment by hirsch88** [comment]
@clastzoo we need to define the z-index levels for our overlays

**Comment by clastzoo** [comment]
![Image](https://user-images.githubusercontent.com/62377419/191464330-44606b3f-1f4a-4b81-a9f5-fccda86c93f5.png)

**Comment by clastzoo** [comment]
https://www.smashingmagazine.com/2021/02/css-z-index-large-projects/

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/792
