### ISSUE TITLE
Additional text does not fit in product slider

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#315]
Proposal by @clastzoo &  @Gagne87: 

- Width of the cards stays as it is
- Height (of all cards) is dynamic and adjusts according to the longest text of the product slider
- The add-on of the text should be displayed in a light font (font-weight:400)
- Card shadow is added to cards (to make action more understandable)

Compare to designs in Figma.

**Comment by hirsch88** [comment]
What is the state here?

**Comment by hirsch88** [comment]
- [x] check with long test which are in the Figma

**Comment by clastzoo** [comment]
![Image](https://user-images.githubusercontent.com/62377419/191451003-f65ab6aa-ce30-4174-9078-66e1ffaf05ff.png)

**Comment by hirsch88** [comment]
- [ ] fix the alignment to top
- [ ] adjust height for 3 lines
