### ISSUE TITLE
Tabs-Steps: behavior differs between angular-dev mode and angular-prod mode

### ISSUE THREAD

**Issue by svene** [baloise-incubator/design-system#337]
## Detailed description

When we use the tabs/steps component in our angular-app it behaves as expected.
But as soon as we use the production-built version of it it behaves differently.
For example we experience that the disabling and enabling of steps do not work as expected in prod mode.

> Describe in detail the issue you're having.

> What did you expect to happen?
That the behavior of the prod-version is the same as the dev-version

> What browser are you working in?
chrome

> Videos
Local Dev Mode (port 4200). This is the behavior we expect:
![bds-stepper-local-dev](https://user-images.githubusercontent.com/51710/183848735-5f1ddc5b-639a-434f-8ed2-a5c33f12ee38.gif)

Local Prod Mode (port 7777). This is the behavior we do not expect:

![bds-stepper-local-prod](https://user-images.githubusercontent.com/51710/183849044-9ade8d47-d75c-4d9d-a1b7-1a97566158e4.gif)

**Comment by hirsch88** [comment]
add reflect true to the props disabled and so

**Comment by hirsch88** [comment]
bal-tab-item add the above prop option to the state props, disabled, hidden, done, failed ...

**Comment by svene** [comment]
I wanted to test the fix but ran into another problem I reported here:
https://github.com/baloise-incubator/design-system/issues/427
Until 427 is resolved this issue is blocked for me.
