### ISSUE TITLE
Can internal project release already the rebrand version?

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#338]
@alexsoeres

**Comment by hirsch88** [comment]
@joachimprinzbach is that possible?

**Comment by joachimprinzbach** [comment]
Discuss with Michael Besel first
- internal projects can already go live

**Comment by joachimprinzbach** [comment]
- website of design system will still be password protected until go live
- repositories can be merged sooner, packages can be aligned before go live

**Comment by christophgeering** [comment]
Internal applications: OK to go live before October 28th.
