### ISSUE TITLE
Interaction concept for Toast & Snackbar

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#345]
Currently the difference between Snackbar, Toast are not really big. We have to create a concept where those elements can be used and how they are implemented.

[Design](https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=2353%3A11895)

**Comment by clastzoo** [comment]
@clastzoo please define ticket

**Comment by clastzoo** [comment]
Might be clever to re-think this ticket after go-live.

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/789
