### ISSUE TITLE
Github Actions usage limit reached

### ISSUE THREAD

**Issue by culmat** [baloise-incubator/design-system#351]
## Summary

The design system actions use the incubator organisations free resources in less than half a month.

## Relevant information
[82729626_2022-08-12_7.csv](https://github.com/baloise-incubator/design-system/files/9316718/82729626_2022-08-12_7.csv)

**Comment by joachimprinzbach** [comment]
Thanks @culmat for the hint. 
We made the repository public, so the problem should be solved now (free org ressources are only consumed by private repos, public repos have no limits).
