### ISSUE TITLE
Self-Service Template

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#357]
1. Custom page template without DS components
2. Header and Footer should be implemented with scoped CSS

Why so that the integration of our calculators is as smooth as possible and we will not face any catches of different DS versions on the page.

@janineKleessen 
@m4rc0z

**Comment by hirsch88** [comment]
@max-voss Would that be possible?

**Comment by hirsch88** [comment]
@max-voss will create a simple magnolia template without the DS

**Comment by hirsch88** [comment]
this bug should be fixed with the new template => https://github.com/orgs/baloise-incubator/projects/2/views/1

**Comment by joachimprinzbach** [comment]
@hirsch88  Integrated calculator worked well with the new template - anything left here?
