### ISSUE TITLE
Implementation for animated logo

### ISSUE THREAD

**Issue by janineKleessen** [baloise-incubator/design-system#359]
The basilisk part of the Baloise logo in the header has to be animated.
See jiraticket https://jira.ibmix.de/browse/BARE-22.
Animation has to be implemented via lottie library see https://jira.ibmix.de/secure/attachment/286098/Lottie-Logo-Animation.json

**Comment by hirsch88** [comment]
trigger on hover and page load

**Comment by hirsch88** [comment]
add two props animated-on-page-load and animated-on-hover

**Comment by hirsch88** [comment]
use bal-logo component

**Comment by nobilo** [comment]
It looks like animated logo is only logo basilics, it does not contain the text `baloise`, can we get with it. Also the size is not good, its 300x300, pls take a look into the screenshot:
![Screen Shot 2022-08-18 at 15 22 42](https://user-images.githubusercontent.com/11984467/185406011-a1c98102-cc72-4201-b81c-c641ffba03c3.png)

**Comment by nobilo** [comment]
discuss animation itself, it looks like it fades in and out, it is very similar to spinner which does not do that though.

**Comment by clastzoo** [comment]
Animation Request is sent to Cerdric from Meta Design.

**Comment by clastzoo** [comment]
@nobilo could you quickly check if you can work with this?

[BAL_Logo_220825.json.zip](https://github.com/baloise-incubator/design-system/files/9424449/BAL_Logo_220825.json.zip)

**Comment by clastzoo** [comment]
@nobilo here we have the next try

[BAL_Logo_220902.json.zip](https://github.com/baloise-incubator/design-system/files/9476707/BAL_Logo_220902.json.zip)

**Comment by clastzoo** [comment]
MVP Approach Suggestion:

- Use current animation.
- Start animation if a user first time comes to a page or refreshes the page
- On mobile, scale the animation down to the current size
- I would not animate the logo on hover, this can be very confusing, as well i wouldn't animate it on click.

Please add your additional thoughts @Gagne87
