### ISSUE TITLE
Angular ngFor does not use the correct order

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#360]
Create a BalTabs with items and remove dynamically an item in the list and add it again. check if it is at the right position.
@yannickholzenkamp can maybe assist with the reproduction of that issue

**Comment by nobilo** [comment]
Seems like this is not happening anymore, i have tried to recrate it in design-system-examples repo: 
https://github.com/baloise/design-system-examples/blob/main/angular/src/app/app.component.ts#L62

@yannickholzenkamp is this what you had in mind, if not pls reopen this issue :)
