### ISSUE TITLE
Reported spacing issues by IBM X

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#369]
Please support IBM X

https://jira.ibmix.de/browse/BARE-532
https://jira.ibmix.de/browse/BARE-570
https://jira.ibmix.de/browse/BARE-553
https://jira.ibmix.de/browse/BARE-512

**Comment by clastzoo** [comment]
Needs to be double checked after the release today
\

**Comment by clastzoo** [comment]
Currently i am gathering additional use cases and thrive trough magnolia to identify additional issues. Planned is a sync with Max either tmrw or on thrusday.
