### ISSUE TITLE
Broken space in desktop nav tabs icon after tabs css changes

### ISSUE THREAD

**Issue by fabio-tedesco** [baloise-incubator/design-system#371]
## After css changes in bal-tabs now the spacing between the arrow icon and the tab content in the main navigation on desktop is changed/broken

> Please restore the spacing between the arrow icon and the tab content as it was before the changes in bal-tabs css

## Steps to reproduce the issue

1. Open main navigation on desktop
2. Compare the spacing with that one in Figma

**Comment by hirsch88** [comment]
fixed in #500
