### ISSUE TITLE
pattern="tel" on bal-input does not work

### ISSUE THREAD

**Issue by stefanbukovski** [baloise-incubator/design-system#374]
In angular application when I set the pattern field on bal-input via string interpolation or via property binding it does not work.
More specifically, it prevents me from inputting of any kind of characters (could not input numbers nor text).

In the picture below you can see that the field was properly set:

![image](https://user-images.githubusercontent.com/108665216/185145814-389ddac0-5037-4b51-a489-089bf960628a.png)

**Comment by hirsch88** [comment]
here is an example => https://design-system-next.vercel.app/?path=/story/components-form-input--simple-phone-number-input

pattern tel is not a regex
