### ISSUE TITLE
Stepper has deviations from Figma

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#388]
Clarify whats the right implementation. 

![Image](https://user-images.githubusercontent.com/62377419/185887422-1877efaa-31f8-4589-ad25-d1ebbb37a94d.png)

**Comment by hirsch88** [comment]
there are no half steps

**Comment by Gagne87** [comment]
@clastzoo there is a conceptual error in the Figma Design System. I'll put this one in "after Go-Live" as this is non critical. There should be no half steps as Gery mentioned.
