### ISSUE TITLE
Provide all HTML5 Input standard attributes on bal-input/bal-select

### ISSUE THREAD

**Issue by m4rc0z** [baloise-incubator/design-system#389]
In my concrete situation i need the autocomplete and maxlength attribute on the bal-input and bal-select component. Since the bal-input/bal-select use a input under the hood, it would be nice to just provide all the attributes of a HTML5 Input (https://developer.mozilla.org/de/docs/Web/HTML/Element/Input). Should be possible to just map down attributes/inputs. 

What do you think about this?

**Comment by hirsch88** [comment]
this is not possible, however we can map certain props/attrs with needed
