### ISSUE TITLE
Add ValueAccessor for bal-file-upload

### ISSUE THREAD

**Issue by nobilo** [baloise-incubator/design-system#412]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

It would be good that in angular we can work with reactive forms on field of type bal-file-upload.
Currently the error is :
`No value accessor`

**Comment by hirsch88** [comment]
@nobilo please check for the duplicated issue

**Comment by nobilo** [comment]
its in the old one so we will leave it here :)

**Comment by nobilo** [comment]
https://github.com/baloise/design-system/issues/653
At the moment we dont have value accessor for this component, so we were forced to override the value of the component and create workaround with it.

The use case where we need it is when the form has few steps(a wizard), and when the user leaves the page where the bal-file-upload is, after he's back, none of the files is shown to him. As said, for current purpose, this behaviour is overridden, but would need the accessor for these cases.

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/722
