### ISSUE TITLE
typeahead remote popover styling issue when no options available

### ISSUE THREAD

**Issue by m4rc0z** [baloise-incubator/design-system#413]
If i use a typahead remote and there are no options available still the pop over appears and covers the validation message.

see: 

![image](https://user-images.githubusercontent.com/20516386/186885824-1c3b3ab8-e3fd-4778-b5e5-9e33b99bf06e.png)

example code:

`
<bal-field>
    <bal-field-label [attr.data-scrollto-target-id]="nameStreet">{{ streetLabel }}</bal-field-label>
    <bal-field-control>
      <bal-select
        *ngIf="showTypeahead"
        [formControlName]="nameStreet"
        (balChange)="onSelectedItem($event)"
        [typeahead]="true"
        [remote]="true"
        [disabled]="disabled"
        (balInput)="streetInputChanged$$.next($event.detail)"
      >
        <bal-select-option
          *ngFor="let option of streetNames$ | async"
          [value]="option"
          [label]="option"
        >
          {{ option }}
        </bal-select-option>
      </bal-select>
    </bal-field-control>
    <bal-field-message *ngIf="formControlStreet.touched && formControlStreet.errors" color=danger>
        <span [attr.data-scrollto-id]="nameStreet"
              [attr.data-test-id]="'validationMessage'">{{formControlStreet.errors | validationMessage: nameStreet}}</span>
    </bal-field-message>
  </bal-field>
`

Should ths popover only be displayed when options are available?

**Comment by hirsch88** [comment]
@nobilo create a new prop to be able to add values which are not available in the options list

**Comment by hirsch88** [comment]
@m4rc0z try to use the prop noDataLabel and set a label



![Image](https://user-images.githubusercontent.com/6384499/190903070-4e5efcd1-5852-4a36-8ca7-c4fe11077d5e.png)

**Comment by m4rc0z** [comment]
Works for us.
