### ISSUE TITLE
typeahead validations

### ISSUE THREAD

**Issue by m4rc0z** [baloise-incubator/design-system#414]
The typeahead currently works the following way:

- it only sets the angular reactive forms formcontrol value when the value is valid (value is inside the available options)

This is a drawback for the enduser which is using the typeahead. What about beeing not that strict and also allow to set values which are not present in the options? This would lead to more flexibility for the consumer of the typehead. 

Before the rebranding we had in our application validations on the remote typehead like:
- maxlength
- async validator of angular to validate if the street is valid

But currently we could only show a validation message if its not valid. We can not give the enduser a more specific validation message since the formcontrol value gets only set when the value which was typed into the typeahead was valid.

**Comment by nobilo** [comment]
We should create a new prop to be able to add values which are not available in the options list

**Comment by hirsch88** [comment]
@m4rc0z max length and the new prop selectionOptional is added please try with them

**Comment by m4rc0z** [comment]
@hirsch88 i have tested it. The "selectionOptional" works like charm thanks 👍 

From the maxlength i would expect that if i set it, the user is not able to type in more characters than the number i provided to the maxlength property. This is not working for me. Did I misunderstand something?
