### ISSUE TITLE
add autocomplete attribute to the typeahead/typeahead remote

### ISSUE THREAD

**Issue by m4rc0z** [baloise-incubator/design-system#415]
We would like to have the autocomplete attribute on the typeahead remote component. On that way the user can profit from the autocomplete feature the same way as it was before within the client libs.

**Comment by nobilo** [comment]
hey @m4rc0z  have you maybe tried it on bal-input does it work there?

**Comment by m4rc0z** [comment]
i have tried it there and there the autofill feature does not work but the autocomplete feature does work.
