### ISSUE TITLE
Highlight Box Component

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#417]
I ran into several use cases where a "highlightbox" would be needed. Any ideas / suggestions for this topic?

![Image](https://user-images.githubusercontent.com/62377419/186915013-bc8bc30b-73b0-4a2f-8579-a6523adf98ec.png)

![Image](https://user-images.githubusercontent.com/62377419/186915035-c473ec48-8989-4b2b-8b90-815be00de6d9.png)

**Comment by hirsch88** [comment]
could this help => https://design-system-next.vercel.app/?path=/story/components-notice-notification--basic&args=color:info
