### ISSUE TITLE
New WAF Error/Maintenance Pages Design

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#420]
cc:

Die  WAF Seiten benötigen ein Relaunc-Design.. siehe die diversen jetzigen Pages hier im Ticket angehängt:
https://jira.baloisenet.com/atlassian/browse/SUCOM-1138
Ich liefere dann den Content.

**Comment by christophgeering** [comment]
Static page needed for down times

**Comment by joachimprinzbach** [comment]
finished, marketing does a last check.
