### ISSUE TITLE
Discuss finding a better solution to implement icons in Native list

### ISSUE THREAD

**Issue by mladenplaninicic** [baloise-incubator/design-system#425]
Discuss finding a better solution to handle spacings between the icon and the text in the Native list

**Comment by joachimprinzbach** [comment]
convert it from a pseudo class to a container to get more control?

**Comment by hirsch88** [comment]
lets talk with @max-voss how to solve that

**Comment by hirsch88** [comment]
@max-voss will get a list with all the needed icons. after that we gonna talk about the solution

**Comment by hirsch88** [comment]
normal UL => hooks
ring list => small dot - first styling Bullet List 3.06
PDF, PPT and XLS => will be replaced with common document icon Download List 3.05
arrow list => small dot - first styling Bullet List 3.06

**Comment by hirsch88** [comment]
@janineKleessen do you now which other icons we need for the list icons

**Comment by hirsch88** [comment]
done
