### ISSUE TITLE
[bal-image-slider], do not swipe on mobile click

### ISSUE THREAD

**Issue by Sw0rdiX** [baloise-incubator/design-system#434]
## Detailed description

in mobile view the user should use a swipe and not a click for rotate to the next or previous slide.
in our case, if i have custom content in the slide item and have in this case a back-side. i can reach it over the info button. then i click on the button and a previous slide item is available it will show me the back-side and also rotate to the previous slider item.

## Steps to reproduce the issue

1. open site in mobile view with touch access
2. click on the slider-item at the right or left side
3. the slide moves left or right

## Additional information

https://user-images.githubusercontent.com/3681337/187693724-166b7b7c-47ac-42ea-8b3b-ae3cddc91d41.mov

**Comment by clastzoo** [comment]
I identified several additional issues, we have to disucss the process tmrw in the daily.

**Comment by hirsch88** [comment]
check product slider as well with the touch navigation

**Comment by Gagne87** [comment]
#508
