### ISSUE TITLE
Discuss about how text needs to be aligned in Stage component

### ISSUE THREAD

**Issue by mladenplaninicic** [baloise-incubator/design-system#447]
When we don't have a subtitle in the example the text goes down, the same problem we have when the image height is big. That is happening because we have justify-content: flex-end; on bal-stage-body. 

We should define how text needs to be aligned here.

![Image](https://user-images.githubusercontent.com/28272339/188124234-f116b703-a723-45f5-a14f-8976b1d27bfb.png)

![Image](https://user-images.githubusercontent.com/28272339/188123544-3ed62fef-f190-4858-9322-095611b94560.png)

**Comment by hirsch88** [comment]
@GinaBiondo-aperto lets check the stage together what we need and what not

**Comment by hirsch88** [comment]
@GinaBiondo-aperto will add the needed sizes with values and we gone fix the stage with alignment and sizes

**Comment by GinaBiondo** [comment]
Hey @hirsch88 :)

So on our side, there are only two sizes currently used. Medium with 400px and large with 840px. Small seems to be defined by the content and the other ones are not in use.
