### ISSUE TITLE
bal-select: 'touched' property broken in latest version ?

### ISSUE THREAD

**Issue by svene** [baloise-incubator/design-system#453]
## Detailed description

In our angular-DS-app we use the property 'touched' of formcontrols to show field errors.
When we step through the form with a tab key they become red when not filled in correctly.

I attached two small videos to this issue:
the first one shows the behavior with version 10.15.7 where the behavior is as expected.
the second one shows the behavior with version 10.20.2 where property 'touched' of the formcontrol is not updated
correctly (note that in this second video the value of 'touched' is shown below the field for debug purposes).

> What did you expect to happen? What happened instead? What would you like to see changed?
Behavior as in first video to be restored.

> What browser are you working in?
chrome

First video:
![bal-select_touched-10 15 7](https://user-images.githubusercontent.com/51710/188436738-b5ba748c-30a5-4848-ab41-224361a49618.gif)

Second video ( 10.20.2): 
![bal-select_touched-10 20 2](https://user-images.githubusercontent.com/51710/188436829-1609789a-b16c-4f44-944f-0d8c4ed701aa.gif)

**Comment by hirsch88** [comment]
#623 connected issue

**Comment by nobilo** [comment]
@svene pls check with version [v10.24.1](https://github.com/baloise-incubator/design-system/releases/tag/v10.24.1)

**Comment by m4rc0z** [comment]
works 👍
