### ISSUE TITLE
Adjust TCS Teaser

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#465]
The client want's to adjust the header of the tcs implementation.

- Add number to header in numbers, no icon
- Add application title to the header

![Image](https://user-images.githubusercontent.com/62377419/188669636-353850b4-47a4-404b-a68d-fca04a3e48b7.png)

Deliver Design for IBM

**Comment by hirsch88** [comment]
@clastzoo   inform them to use the bal-navbar

**Comment by joachimprinzbach** [comment]
Wrote an email to Katja Wussler to inform her
