### ISSUE TITLE
[bal-tabs] unable to center the tab items

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#466]
Can you please add the option to center the tab items? For the time being, there is only the possibility to align them to the start or to the end.

where is needed: https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=4008%3A50604

**Comment by hirsch88** [comment]
@madaluca please align it to the left
