### ISSUE TITLE
Update Grid Container in DS Documentation and Figma

### ISSUE THREAD

**Issue by GinaBiondo** [baloise-incubator/design-system#470]
## Discrepancies between design and implementation

Currently, there are two versions for the tablet padding on the container present. Implemented is a padding of 32px left and right but many design files show padding of 48px. Which one should be used? :)

Figma:
![Bildschirmfoto 2022-09-07 um 11 16 33](https://user-images.githubusercontent.com/72393447/188841114-ed32e8bb-71ff-459e-83a0-48b95e64952f.png)

Implemented Container Padding:
![Bildschirmfoto 2022-09-07 um 11 17 38](https://user-images.githubusercontent.com/72393447/188841363-e3b032c4-ccc2-422b-9f77-8ae118e6eb73.png)

**Comment by clastzoo** [comment]
### **Comment can be ignored**

![Image](https://user-images.githubusercontent.com/62377419/189688680-20e3d65b-0d80-4636-b328-6efce078f6ad.png)

This might answer the question? 
https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=110%3A893

**Comment by hirsch88** [comment]
it is done in the technical ds

**Comment by hirsch88** [comment]
@clastzoo please update the docs as well

https://design-system-next.vercel.app/?path=/docs/design-css-framework--container#container

**Comment by clastzoo** [comment]
@hirsch88 we need to quickly sync on monday for the container/grid differentiation. as welle the markup tables.
