### ISSUE TITLE
Datepicker emits `balChange` with empty string after form is submitted

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#474]
## Detailed description
When selecting date - datepicker sets correct value but after leaving it blank and submitting form `balChange` event is emitted after form is submitted and value is set as empty string `""` on the next screen after validation is done.

> What did you expect to happen? What happened instead? What would you like to see changed?

In previous versions (10.4.4) datepicker did not emit `balChange` event in this case.

> What browser are you working in?

Google Chrome
Version 105.0.5195.102
## Steps to reproduce the issue

1. Select value in the datepicker
2. Remove value
3. Without clicking anywhere else click on the `next` button

Please ping if any additional information needed

## Additional information
![form-submitting-issue](https://user-images.githubusercontent.com/35540320/188879939-452487c7-4d54-4b57-a0ba-846da27bc4f4.gif)

**Comment by hirsch88** [comment]
@BerSteve does this happen also on the newest version ? 

could not reproduce it :-(
change event was fired before the submit event see logs

<img width="515" alt="image" src="https://user-images.githubusercontent.com/6384499/190894164-625ed231-087b-47aa-a9f3-4b9d6828d6d2.png">

**Comment by BerSteve** [comment]
Hey @hirsch88, thanks for investigation, seems like with latest updates on your end or ours (or both:) ) issue is partially fixed. I think because of our platform specifics there is one more edge case which will be handled on our side.
