### ISSUE TITLE
Links are no longer underlined

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#476]
## Summary
Links are no longer underlined, is this on purpose?

## Relevant information
![Screenshot 2022-09-07 at 15 56 38](https://user-images.githubusercontent.com/35540320/188885071-34f18667-46fe-4f8e-9eb3-42c3e5762977.png)
![Screenshot 2022-09-07 at 15 57 48](https://user-images.githubusercontent.com/35540320/188883846-5e4b32b7-4c74-4ee1-94e7-5815b2e5df16.png)

**Comment by hirsch88** [comment]
https://design-system-next.vercel.app/?path=/story/components-button--native-link

**Comment by hirsch88** [comment]
`<a class="is-link">Link</a>`

**Comment by hirsch88** [comment]
@BerSteve please add the class `is-link` to it
