### ISSUE TITLE
[bal-navbar]: do not show `burger menu` if no menu items are defined

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#479]
## Detailed description
`bal-navbar` renders empty `burger` menu button even though there is nothing to display (navbar has only logo).

Burger menu should not be shown if nothing is defined in menu.

## Steps to reproduce the issue

```
<bal-navbar interface="app">
  <bal-navbar-brand>
    <bal-logo brand="group" color="white"></bal-logo>
  </bal-navbar-brand>
</bal-navbar>
```

## Additional information
![Screenshot 2022-09-07 at 16 42 54](https://user-images.githubusercontent.com/35540320/188893519-2649d8d1-7612-45a8-935e-8d47557508b3.png)

**Comment by hirsch88** [comment]
@BerSteve use interface simple

**Comment by hirsch88** [comment]
https://design-system-next.vercel.app/?path=/story/components-navbar--simple
