### ISSUE TITLE
[sass injection] provide no css for sass only imports -> baloise-design-system.utilities.sass

### ISSUE THREAD

**Issue by Sw0rdiX** [baloise-incubator/design-system#483]
## Detailed description

<img width="733" alt="tokens split css root " src="https://user-images.githubusercontent.com/3681337/188999367-d837308c-42f1-466f-832c-5c3b163502c5.png">

- tokens.sass => split :root out for sass vars only imports

<img width="880" alt="typography split css root" src="https://user-images.githubusercontent.com/3681337/188999372-65637f05-3f7c-4860-977f-83dc33bba369.png">

- typography.vars.sass => split :root out for sass vars only imports

<img width="879" alt="split fonts as extra import" src="https://user-images.githubusercontent.com/3681337/188999770-1ba6099c-369d-4008-bc84-f11e63f15001.png">

- fonts.sass => split @font-face out for sass vars only imports

**Comment by joachimprinzbach** [comment]
Hey @Sw0rdiX 
we won't be able to tackle this one before go live. 
We accept PR's or are happy to have a look at it afterwards.

**Comment by hirsch88** [comment]
is done
