### ISSUE TITLE
[bal-hint]: Single word title is breaking to new line

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#488]
## Summary
Title is being broken to the new line, seems like there would be enough space to make it one liner on desktops. What do you think?

## Relevant information
Current:
![Screenshot 2022-09-08 at 09 25 49](https://user-images.githubusercontent.com/35540320/189049848-fad3f4e5-d05e-4ecd-a8db-b3e2b349c546.png)
Suggestion:
![Screenshot 2022-09-08 at 09 32 47](https://user-images.githubusercontent.com/35540320/189051095-0801b237-dac4-4ed4-af9f-29d811c848ed.png)

**Comment by joachimprinzbach** [comment]
@BerSteve Could you try to upgrade to the latest version and see whether the issue still occurs?

**Comment by BerSteve** [comment]
@joachimprinzbach Upgraded, still breaks to new line, but looks nicer with the dash `-`. Feel free to close
<img width="263" alt="Screenshot 2022-09-29 at 17 02 57" src="https://user-images.githubusercontent.com/35540320/193052896-b9d7ae76-bfb3-4d34-8db5-9f297e9c2eb7.png">
