### ISSUE TITLE
the new visual appearance of the option button

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#492]
## Detailed description
After using the newest version of DS, areas in our application look different and are now different from our previous developed mockup:
This is about the change of the visual appearance of the **option button** component. It now contains in addition
a circle (probably an option field) in addition to the label. 
In addition, the option buttons no longer extend the whole width of the area.

We in the team are not happy with this appearance and fear that the user will be confused by this unknown component. And our application no longer looks as "beautiful" as before. 

**Suggested solution:** 
Is it possible to switch the circle in the component on and off via parameter?
Another parameter for expand over the complete width?

We are available for discussions in person

**this is the original design**
![image](https://user-images.githubusercontent.com/292344/189057848-4a16abdc-408d-4e2f-8359-1b2288c6932c.png)

**In our eyes, these areas no longer look optimal:**
![image](https://user-images.githubusercontent.com/292344/189057488-5e90865b-b5ad-4663-a882-5a612b6923aa.png)
![image](https://user-images.githubusercontent.com/292344/189057532-a265def6-4a4c-4884-a4e3-c42694339fda.png)
![image](https://user-images.githubusercontent.com/292344/189057571-9d4b5afe-c9a9-432a-9086-5fcc50dc5ee5.png)

**Comment by joachimprinzbach** [comment]
Hey @tklueber 
we moved this issue to "after go live" - therefore we won't work on this before november. 
If you have questions or want to discuss, feel free to contact me.
