### ISSUE TITLE
[bal-icon] 'Arrows Round Left' icon is missing

### ISSUE THREAD

**Issue by mihaiconstantin2** [baloise-incubator/design-system#494]
<img width="71" alt="Screenshot 2022-09-08 at 10 58 05" src="https://user-images.githubusercontent.com/113094467/189067918-1411c1b3-4ca8-4fb8-b48b-95aa1bda7da2.png">

**Comment by clastzoo** [comment]
Please add this icon to the ds.

![Image](https://user-images.githubusercontent.com/62377419/189620221-8c736fe5-35b0-41e1-a924-e4cddaf42874.svg)
