### ISSUE TITLE
[bal-icon] 'Help Customer Support' icon is missing

### ISSUE THREAD

**Issue by mihaiconstantin2** [baloise-incubator/design-system#495]
<img width="184" alt="Screenshot 2022-09-08 at 11 45 50" src="https://user-images.githubusercontent.com/113094467/189078071-f434d645-2139-4765-a3b1-4be8c3c890de.png">

**Comment by clastzoo** [comment]
@Gagne87 added it to Figma too. 

![Image](https://user-images.githubusercontent.com/62377419/189634447-9629e091-3b15-4659-ab85-abdd1bd0b71a.svg)
