### ISSUE TITLE
[date-picker] Mobile Bugs

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#497]
### Bug 1
Date Picker is overlaying everything, the field below is selected, and the cursor is blinking. The user can't edit the field.

### Bug 2
If the users scrolls, the date picker won't stay aligned to the input field. Same appears if a month has more date, then the overlay grows over the input field.

https://user-images.githubusercontent.com/62377419/189623634-1cd53d92-e6a3-4216-9940-40906541f792.mp4

### Additional Solution

Solution discussed with @hirsch88 
1. Touch opens the date picker
2. Touch will select the date-input characters, so the user can natively use the keyboard to enter the value.

**Comment by hirsch88** [comment]
fixed with new iOS version on my site

**Comment by Gagne87** [comment]
@clastzoo will re-investigate bugs and add a description.

**Comment by hirsch88** [comment]
will be done by [#207](https://github.com/baloise-incubator/design-system/issues/207)
