### ISSUE TITLE
[bal-button] Implement correct touchstates for all buttons

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#498]
Default State 
Pressed State
Selected State

https://user-images.githubusercontent.com/62377419/189100818-fef74088-4d1f-4176-a28d-aab3dd4d3aaa.mp4

https://user-images.githubusercontent.com/62377419/189157972-3dd01d31-26de-428e-bf7c-4d5da94e77bb.mp4

Focus state appears before pressed state

**Comment by Gagne87** [comment]
@clastzoo will create a ticket for radios and checkboxes. Rest will be tackled after Go-Live.

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/720
