### ISSUE TITLE
Hyphen support for all components

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#499]
In the current implementation we don't have a proper line break. how can we avoid this?

![Image](https://user-images.githubusercontent.com/62377419/189116048-6151b47e-8c0a-4cf4-9744-eaca56b29bea.png)

**Comment by hirsch88** [comment]
add hyphen css attribute

**Comment by clastzoo** [comment]
let's further investigate in the hypen solution. @mladenplaninicic & @Gagne87

**Comment by Gagne87** [comment]
@mladenplaninicic just investigated how the "hypens" property works and tried it out locally. 
Hypens uses the "lang" attribute of the page. According to which language is set there "hypens: auto" solves the problem with the breaks.

**Comment by hirsch88** [comment]
- [ ] check every component where there are text elements that they have hyphen=auto
