### ISSUE TITLE
[bal-field] Search: the button should be below the input on mobile

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#501]
Can you please add also an example with the button bellow the input, on mobile resolution, like in the following screenshot?
![Screenshot 2022-09-09 at 13 05 23](https://user-images.githubusercontent.com/17945926/189326085-7df3a6a1-2209-4009-a556-a87806ab744c.png)
Here you can find the design for all resolutions: https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=4008%3A50604

Current DS implementation
https://design-system-next.vercel.app/?path=/story/components-form-field--addon

**Comment by Gagne87** [comment]
Decision: Own property has to be created to display input & button in two different rows (vertical alignment on mobile).
