### ISSUE TITLE
[multi-select] need variant without tags

### ISSUE THREAD

**Issue by Sw0rdiX** [baloise-incubator/design-system#503]
we need also a multi-select in the variant with the following acceptance criteria

- Activity Dropdown with Placeholder and Checkbox list with apply/close-button

old variant
![image](https://user-images.githubusercontent.com/3681337/189353765-fd628ce4-11a6-47cf-89af-4a6b229fc05f.png)

https://www.baloise.com/de/jobs/alle-jobangebote.html)

**Comment by Gagne87** [comment]
@Sw0rdiX could we go with the standard design system component using tags for now? Atm we don't see the immediate need for it.

**Comment by Sw0rdiX** [comment]
have to speak with my PO :)
