### ISSUE TITLE
[bal-radio - select-button] remove radio circle

### ISSUE THREAD

**Issue by max-voss** [baloise-incubator/design-system#517]
## Detailed description

According to Designs, the select-button variation of the radio should have no visible radio-circle, see [Figma](https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=165%3A520)

Selected state is different, too

## Additional information

IS:
<img width="411" alt="Bildschirmfoto 2022-09-12 um 16 07 42" src="https://user-images.githubusercontent.com/29964860/189675232-8c8f0b0d-8210-4aee-b8b9-d3b2afc0d301.png">

SHOULD:
<img width="609" alt="Bildschirmfoto 2022-09-12 um 16 08 36" src="https://user-images.githubusercontent.com/29964860/189675379-3ff4c95a-6897-41c2-91a1-6d06644bb636.png">

**Comment by clastzoo** [comment]
I've informed Caroline from IBMIX she's aware that for forms we should use the normal radios. 
The radios where designed in the components.
