### ISSUE TITLE
Select should allow selection by typing #656 old repo

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#520]
by @Tiliavir

On bal-selects without typeahead, it should be possible to select options by typing the first letters.
Currently it is only possible to navigate through the list with arrow keys or using the mouse.

On bigger lists, this is a bit tedious.

Hi @LaurentSteiner , Hi @hirsch88

after discussing my initial suggestion with Laurent, I've updated the issue above.

Thanks for your effort
Markus

**Comment by joachimprinzbach** [comment]
Hey @Tiliavir 
we are not going to tackle this issue before go live. If you have questions or want to challenge this decision, feel free to contact me.

**Comment by joachimprinzbach** [comment]
![image](https://user-images.githubusercontent.com/4256585/190422677-163778ff-3c5e-4a94-bf4f-029a6a1768b1.png)

**Comment by joachimprinzbach** [comment]
Entering e.g. "Mo" should filter the list (even though the input won't be visible).
See https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select and click the car model selector and press "a" -> Audi is selcted. That would be the required behavior
