### ISSUE TITLE
[bal-select, bal-checkbox, bal-radio] setFocus not focusing input-element

### ISSUE THREAD

**Issue by max-voss** [baloise-incubator/design-system#523]
## Detailed description

Programmatically triggering setFocus - e.g. while validating - scrolls to the correct element but the mentioned bal components don't focus the correct inputs and/or don't show the right focussed state

**Comment by hirsch88** [comment]
let discuss that in the tech daily @max-voss

**Comment by hirsch88** [comment]
done with #500
