### ISSUE TITLE
[bal-footer]: `Baloise Group` link leads to wrong language url

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#524]
## Detailed description

Selecting  language `DE` and opening `Baloise Group`, link leads to english version `(https://www.baloise.com/en/home.html).`
Selecting  language `IT` and opening `Baloise Group`, link leads to french version `(https://www.baloise.com/fr/home.html).`

![Screenshot 2022-09-14 at 00 27 35](https://user-images.githubusercontent.com/35540320/190012466-02fe331e-c55c-4eee-b83a-a150e4f1d668.png)

**Comment by hirsch88** [comment]
Looks like it is not correct done in magnolia.
@clastzoo could you please inform Janis

**Comment by hirsch88** [comment]
linked to #525

**Comment by clastzoo** [comment]
![Image](https://user-images.githubusercontent.com/62377419/191249144-f7d72c14-d81b-4c42-b3ba-ed9115925bd0.png)

**Comment by clastzoo** [comment]
I will have to talk to Loic to fix it directly in Magnolia.

**Comment by joachimprinzbach** [comment]
"link_3": {
          "link": "https://www.baloise.ch/it/chi-siamo/cookie-policy.html",
          "label": "Cookie Policy"
        },
        "link_4": {
          "link": "https://www.baloise.com/fr/home",
          "label": "Baloise Group"
        }


--> For italian the link is wrong in the app integration json

**Comment by joachimprinzbach** [comment]
"link_3": {
          "link": "https://www.baloise.ch/de/ueber-uns/cookie-policy.html",
          "label": "Cookie Policy"
        },
        "link_4": {
          "link": "http://www.baloise.com",
          "label": "Baloise Group"
        }

--> German link has no language and therefore uses user / browser default lang, what could be the reason why @BerSteve get's it in English.

**Comment by joachimprinzbach** [comment]
We could otherwise change it to: http://www.baloise.com/de/home

**Comment by joachimprinzbach** [comment]
@Gagne87 There is no italian site... 
![image](https://user-images.githubusercontent.com/4256585/191947138-df561b86-d797-4609-9082-73edf755bb68.png)

**Comment by joachimprinzbach** [comment]
See: https://www.baloise.com/fr/home.html

**Comment by Gagne87** [comment]
@joachimprinzbach & @clastzoo: Just had a call with Jannis. Following outcomes: 

- IT does not exist on the .com website and therefore should be pointing on FR 
- The links can be changed on the CH Magnolia instance 
- Links should be changed by someone from the content team as Jannis is not allowed to (I could also do it as I have the permission there) 

Please let's discuss on Monday in the daily. 

Thanks. Laurent

**Comment by christophgeering** [comment]
Decision: Let's do this @Gagne87
