### ISSUE TITLE
check app integration api on the new environment

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#525]
https://www.baloise.ch/app-integration/footer-links/de.json that's the old we need to check if the new one exists and works

**Comment by hirsch88** [comment]
@Gagne87 & @clastzoo could you check it

**Comment by joachimprinzbach** [comment]
@Gagne87 @clastzoo @hirsch88 there is no difference in the de.json btw current prod and rebranded int environment.
