### ISSUE TITLE
Expose `initialize` method in `window`

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#526]
### Summary

For development: would it be possible to expose [initialize](https://github.com/baloise-incubator/design-system/blob/ecb670bc32bb681ad9386eabf1391c7a48200bca/packages/components/src/config/initialize.ts#L12) method in `window` object?

### Justification

Since `locale` properties in components are being deprecated another way of setting language for datepicker and footer is needed.
Currently we are using baloise design-system by importing it via cdn into `document`, so only features that are exposed in `window` object [here](https://github.com/baloise-incubator/design-system/blob/next/packages/components/src/global.ts) are available.

**Comment by joachimprinzbach** [comment]
Hey @BerSteve 
as there is an existing workaround, we will work on this issue with lower priority. I can therefore not guarantee a resolution before go-live. If you any questions, do not hesitate contacting me.

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/713
