### ISSUE TITLE
Do the big release

### ISSUE THREAD

**Issue by nobilo** [baloise-incubator/design-system#530]
### Summary

We should merge next repo with non-next repo and do the big major release

### Justification

We should this so every user of our lib has stable major version of design system

**Comment by hirsch88** [comment]
- [x] vercel public
- [x] remove major build on old one
- [x] fix tabs issues
- [x] fix select issues
- [x] fix nav issues
- [x] rename the npm package name without next
- [x] remove all the -next in the documentation
- [x] release next as version 11
- [x] adjust changelog
- [x] change Vercel domain names
- [x] add link to new DS in the old one
- [x] examples need to use the new version 11
- [x] update the web-app-ng-utils

**Comment by Gagne87** [comment]
Moved to Tuesday next week due to some bugs that have to be resolved first.
