### ISSUE TITLE
[bal-navigation] - bug report

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#533]
### Safari Issues General

Attribute flex gap is not supported on 14.XX Safari, removes all the paddings. https://github.com/baloise-incubator/design-system/issues/532

![Image](https://user-images.githubusercontent.com/62377419/190676985-e2f5ff8b-c49c-4c62-96eb-d4eacff1d846.png)

### Desktop

- [x] Border Radius transition got lost 

![Image](https://user-images.githubusercontent.com/62377419/190672640-7c264a42-f8f3-4474-b9aa-b3da8a06afff.png)

- [x] Breakpoint Issue, white bar shouldn't touch the viewport `Lets discuss in a session`

![Image](https://user-images.githubusercontent.com/62377419/190673470-76ca8142-f630-465c-baa2-87a618830b31.png)

- [x] Framedrops on browser resize `not mvp relevant`

https://user-images.githubusercontent.com/62377419/190674401-41a5d47b-22a4-4fd1-9ea5-1bd7ddddad83.mov

- [x] Scroll Behaviour has to be double checked, it seems like sometimes the overlay box is not actice (All browser desktop) Contact @clastzoo to show more issue of this bug. 

https://user-images.githubusercontent.com/62377419/190675768-dc28b479-00ac-4beb-a132-68ba52fe1d52.mov

### Tablet

**IOS**

- [x] Search Popover adjusts wiredly, Safari, Firefox, Brave a working correctly. 

![Image](https://user-images.githubusercontent.com/62377419/190469519-30315a59-ca4d-435b-af5f-2e78cea0ef5b.PNG)

### Mobile

**IOS**

Safari, Chrome,Firefox
- [x] Overflow issue when the user swipe over the gap on the bottom of the page. 

![Image](https://user-images.githubusercontent.com/62377419/190666327-0bf15e5b-e80a-49ba-aed7-ab89690e201b.png)

Some minor issues on landscape mode but not MVP relevant for now.

**Android**
No issues found  🎉🎉🎉🎉

**Comment by Gagne87** [comment]
Moved to prio2 as nothing is breaking.

**Comment by hirsch88** [comment]
https://gist.github.com/nicolaskopp/637aa4e20c66fe41a6ea2a0773935f6e

to fix the search popover scroll to top issue on iOS

**Comment by clastzoo** [comment]
thanks for fixing the issues @hirsch88 

i only found the wired popover behaviour – the rest is working smoothly.

**Comment by Gagne87** [comment]
Waiting for after Gery's vacation.
