### ISSUE TITLE
[Tabs] - Tab overflow implementation

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#535]
### Current Implementation
![Image](https://user-images.githubusercontent.com/62377419/190585484-4c9e8e99-9f17-432f-856a-43ebb4cd1f0e.png)

### Design
![Image](https://user-images.githubusercontent.com/62377419/190586781-91bfa4c4-8075-49c1-833e-dbde9448522e.png)

**Figma**
https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=36390%3A339754&viewport=7274%2C4423%2C0.5

**Quick Prototype**
https://www.figma.com/proto/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?page-id=187%3A2287&node-id=37334%3A329893&viewport=8884%2C5143%2C0.63&scaling=min-zoom&starting-point-node-id=37033%3A329324

**Open to disucss**

Behaviour directions
- Segmented controll to make the hidden item visible 
- Free controll with scroll/drag/click

Animation
- Can we fade in the white softener element?

**Comment by clastzoo** [comment]
Hi @mladenplaninicic i've found the following issues: 


### Global

- [x] Remove Scrollbar
![Image](https://user-images.githubusercontent.com/62377419/192794985-0a528009-d662-46d4-b749-dce1440ba0bf.png)


### Desktop

- [ ] Default behaviour discussion
Can we improve the default state to a minimum `Peer Session`


- [ ] Icon differences 
![Image](https://user-images.githubusercontent.com/62377419/192793756-7bdeb4c9-8cbb-47e3-91e3-4a1717b32207.png)

- [x] Increase white softener area
![Image](https://user-images.githubusercontent.com/62377419/192793955-9256bebf-c0fb-4aea-95e1-5fcb39a4e19e.png)

- [x] Discuss snap-behaviour
![Image](https://user-images.githubusercontent.com/62377419/192794182-cdedbba0-de4a-40c1-a644-103c8df23bb3.png)


### Tablet 

- [x] Icon alignment should be centered
![Image](https://user-images.githubusercontent.com/62377419/192794397-4ab11340-03f7-4844-8d3d-b0ea9fdd6090.png)

**Comment by hirsch88** [comment]
@clastzoo please retest the changes

**Comment by Gagne87** [comment]
I just had a look on desktop (Macbook 16", Brave 1.44.108) and have following finding: 

1. Shadow between button/icon & tab has to be increased (compare to left version of the screenshot > Figma
2. Button/Icon does not look like in Figma > too little padding in the ellipse

<img width="677" alt="image" src="https://user-images.githubusercontent.com/29020214/194832136-ff3dc129-d4a7-4f42-b8c1-ecad8ef19841.png">

**Comment by hirsch88** [comment]
waiting for v12

**Comment by hirsch88** [comment]
done in v13
