### ISSUE TITLE
[Badge] Add color variants

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#537]
Belgium reported, that they would like to have more color variants for the badge component. E.g. they want to use red-3 in the context of the navigation. In my opinion then we should also provide the same color tint for the other base colors. So following has to be done: 

- [ ] Add following 4 colors (red-3, green-3, yellow-3, purple-3) to component with a blue font inside
- [ ] Adapt Figma with the new color versions
- [ ] Communicate change to Belgium (Jesper)

According to Jesper this is not urgent. So does not have to be done before Go-Live. 

#440

![Image](https://user-images.githubusercontent.com/29020214/190602364-764a5f32-a0e4-4a4b-9c7e-479faf223dac.png)

![Image](https://user-images.githubusercontent.com/29020214/190603188-cb71bb55-9c60-4977-acf9-7cd603c450ed.png)

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/719

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/719
