### ISSUE TITLE
[bal-button-group] wrong alignment 

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#562]
**Tablet:** the buttons are aligned correct, but when a button text exceeds the width of the button, the text is aligned to the left.
<img width="236" alt="Screenshot 2022-09-19 at 09 04 43" src="https://user-images.githubusercontent.com/17945926/190958282-eee34335-1402-44e8-be07-4b4c7de533d1.png">

**Mobile:** buttons are aligned to the left, instead of being expanded
<img width="731" alt="Screenshot 2022-09-19 at 09 05 00" src="https://user-images.githubusercontent.com/17945926/190958471-525e8df2-004a-4af3-8089-fa27f020f31f.png">

**Comment by hirsch88** [comment]
will be done in #477

**Comment by madaluca** [comment]
@hirsch88 @mladenplaninicic on mobile, the buttons are still aligned to the left, instead of being expanded
