### ISSUE TITLE
[bal-tabs | steps variant] font-size are 14px instead of 16px for all viewports

### ISSUE THREAD

**Issue by max-voss** [baloise-incubator/design-system#565]
## Detailed description

The number labels of the steps bal-tabs should be 16px for all viewports instead of the 14px currrently used.

**Comment by hirsch88** [comment]
@clastzoo & @Gagne87 will verify the design

**Comment by hirsch88** [comment]
will be done after go live

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/689

**Comment by GinaBiondo** [comment]
Appears again after introducing bal-step component

**Comment by GinaBiondo** [comment]
Correct as implemented
