### ISSUE TITLE
bal-hint bug on mobile resolution

### ISSUE THREAD

**Issue by stefanbukovski** [baloise-incubator/design-system#566]
## Title line template: [Title]:

Content of the bal-hint disappears and some elements that are on the page appear over it in mobile resolution.

## Detailed description

When I resize to mobile resolution and click on the hint icon the hint content box appears but the text that should be displayed inside it disappears and also some other elements that are on the page (inputs, selects...) appear inside it. This also happens if one clicks on the hint on desktop resolution and then resizes to mobile.

Normally the text should be visible and other elements should not interfere (see screenshots). This is also present in the example app.

## Steps to reproduce the issue

1. resize to mobile resolution
2. click on the hint icon

## Additional information

Desktop resolution (normal look): 
![image](https://user-images.githubusercontent.com/108665216/191000725-51d798c9-7605-458a-bf1f-f5d04259dd11.png)

Mobile resolution (wrong look):
![image](https://user-images.githubusercontent.com/108665216/191000591-f5641047-e47f-49e7-b704-79b244393ee9.png)

**Comment by hirsch88** [comment]
@stefanbukovski could not reproduce it

![2022-09-20 10 53 11](https://user-images.githubusercontent.com/6384499/191214007-36fc2050-1236-43cc-902e-db28bfb56bb9.gif)

**Comment by stefanbukovski** [comment]
It is fixed in the latest version
