### ISSUE TITLE
Product Slide - Icon Missing and Ordering not working

### ISSUE THREAD

**Issue by mihaiconstantin2** [baloise-incubator/design-system#572]
The product slider doesn't show all elements(as you can see this here https://design-system-next.vercel.app/?path=/story/components-product-slider--basic) . Also we need to have the width of the next slide item dynamically because we need to use the slider for other components were we don't have the 171 width, like for the subnavigation.

**Comment by hirsch88** [comment]
will be done by @mladenplaninicic with #535

**Comment by hirsch88** [comment]
bug could not to be reproduced will close the ticket

**Comment by mihaiconstantin2** [comment]
we still have this issue on https://baloise-reb.dev.aperto.systems/author/qa-overview/components/Productslider.html

**Comment by janineKleessen** [comment]
solved it on oure system, ticket can be closed
