### ISSUE TITLE
[bal-snackbar] message has a wrong font size

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#574]
actual font size: 16px
expected font size: 12px

**Comment by hirsch88** [comment]
toast have 16px I guess snackbar should have the same ? 
@clastzoo & @Gagne87

**Comment by mladenplaninicic** [comment]
fix the width of the snackbar on the desktop too

![Image](https://user-images.githubusercontent.com/28272339/191462244-cfa33937-d4f4-4f30-a881-77710de3fccb.png)
