### ISSUE TITLE
[bal-navigation]  scrolling issues on Safari 15.6

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#577]
Safari 15.6.1 & Safari 16: When scrolling to the top and reaching the top of the page, the meta nav disappears

https://user-images.githubusercontent.com/17945926/191241062-75196800-b561-4dd4-acb6-0e59bbb25b6f.mov

**Comment by hirsch88** [comment]
need to install the MacOS

**Comment by hirsch88** [comment]
@mladenplaninicic could you test that in safari 16 it works
