### ISSUE TITLE
[Forms] Bug report safari 14

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#594]
Currently in Safari Version 14.0.3 (16610.4.3.1.4), the forms are misaligned.

https://baloise-reb.qa.aperto.systems/baloise-qa/de/smoketest/form-page.html

![Image](https://user-images.githubusercontent.com/62377419/191448008-546d88f0-148c-4a37-bad4-5dc89e2b6b0e.png)
![Image](https://user-images.githubusercontent.com/62377419/191448007-963f03db-5f54-4a98-bc90-c8cbc12dda23.png)
![Image](https://user-images.githubusercontent.com/62377419/191448006-8b5a213d-f24f-4fb4-be4a-68122493c0fc.png)

**Comment by clastzoo** [comment]
@hirsch88 please retest in Safari 15
x

**Comment by hirsch88** [comment]
@clastzoo add browser matrix and discuss that on Friday

**Comment by hirsch88** [comment]
https://baloise.com/unsupported-browsers/be

**Comment by hirsch88** [comment]
https://github.com/baloise/web-app-utils
