### ISSUE TITLE
[bal-datepicker] Future dates break component's UI.

### ISSUE THREAD

**Issue by dstab** [baloise-incubator/design-system#595]
## Detailed description
Datepicker dates that are in the future default back to min date. A properly created UI for the current date values that are not in the [min,max] range
https://user-images.githubusercontent.com/107861285/191451839-c8ef12fd-5d15-45e1-8d9c-05be499e9970.mov
## Steps to reproduce the issue

1. Manually write date that is in the future. Perfect case 12.12.2023

**Comment by Gagne87** [comment]
Hi @dstab, could you provide us with further information e.g. what you have used for min and max values? Thanks a lot.

**Comment by dstab** [comment]
Hi, @Gagne87 
Note: the user types date the following way DD.MM.YYYY, but the component converts it to YYYY-MM-DD, so I will use this format from now on.
It doesn't really matter what you use for these values as long they are outside the range.
What will result in an error if the range is defined as `min`: `1992-05-13` and `max`: `2022-05-13`:
* 1992-03-13, 1990-05-26, 2023-01-01, 2024-06-13, 2022-06-27 and so forth.
The specific issue with year:

If we say that `min`: `1992-05-13` and `max`: `2022-05-13` then as long as I understand, datepicker will create an array from years in between like [1992,1993,1994....,2022]. Nevertheless, if the user input doesn't match any value in this array, in other words, if the user has written something that is not in the range like `1991-05-13` or `2023-05-13` we will see the behavior in the video. It takes multiple button clicks (forward a month, backward a month) to see the correct value.

The specific issue with the month:
There is a very similar issue with months. If the range is from `min`: `1992-05-13` and `max`: `2022-05-13`, but the user input smth like  13.03.1992 then the same issue happens with months (incorrect month will be seen in the UI dropdown and it will not get updated in the UI).

After clicking buttons enough time You will get proper datepicker logic to work but that is because each button updates its state and once it is in the range then datepicker works correctly.
Example: 
* This is the range `min`: `1992-05-13` and `max`: `2022-05-13`;
* User inputs 13.03.1992;
* It gets converted in our component and you receive 1992-03-13.
* We try to click datepicker next month button.
* Nothing will happen (month input will not respond to changes) but the state will get changed to `1992-04-13` (or whatever).
* We click again then you will see the correct month reflecting because the state will get changed to `1992-05-13` which is within the timeframe.

I believe the issue is with this range defining. Everything that is out of the range results in faulty datepicker logic.

Fell free to ask any follow-up questions. :)

Best regards
dstab
