### ISSUE TITLE
[bal-tabs] selectOnMobile: Dropdown on mobile does not show a value "onload"

### ISSUE THREAD

**Issue by rainerblumenthal** [baloise-incubator/design-system#598]
Max V. tested it again… it is an error in the bal-tabs happens only onload, if you resize or turn the device than it doesn't appear. 

https://baloise-reb.dev.aperto.systems/baloise-qa/de/qa/Sprints/Sprint-11/tab-component.html
https://baloise-reb.dev.aperto.systems/baloise-qa/home.html

Emulated on Desktop:
![image](https://user-images.githubusercontent.com/17472781/191470040-a2157967-c672-47ea-b48e-43d39b140ae9.png)

Samsung S21:
![image](https://user-images.githubusercontent.com/17472781/191470016-19f0966c-f142-4c04-ab2f-c4cb7ebb42b1.png)

Emulated on Desktop:
![image](https://user-images.githubusercontent.com/17472781/191470081-8ab1dd51-a3cb-4266-ab51-8e6fedd7e3c4.png)

Samsung S21:
![image](https://user-images.githubusercontent.com/17472781/191470116-ccb35f9b-1997-4fb4-b6f9-83953924aa09.png)

**Comment by rainerblumenthal** [comment]
see also #329

**Comment by hirsch88** [comment]
@max-voss & @rainerblumenthal could you try to reproduce this in storybook? I was not able to do that :-(

**Comment by rainerblumenthal** [comment]
https://design-system-next.vercel.app/?path=/docs/components-tabs--basic 

probably this is the page to retest

**Comment by joachimprinzbach** [comment]
@hirsch88 The behavior in the design-system is, according to @Gagne87, wrong. The tabs should be transformed into a dropdown on mobile.

**Comment by hirsch88** [comment]
@joachimprinzbach they do if you set the prop selectOnMobile to true

https://design-system-next.vercel.app/?path=/story/components-tabs--basic&args=selectOnMobile:true
