### ISSUE TITLE
[bal-slider] styling issues

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#600]
1. Sliding to the most left part of the slider, the corresponding tab of the current slide loses its active state ( issue reported also for image slider #596)
   

https://user-images.githubusercontent.com/17945926/191485697-262f9627-c8ce-4ec8-b0a8-fb637954e48c.mov

2. the shadow of the card inside of the slider item is not visible to the left and right sides, because of the overflow hidden
   
![Screenshot 2022-09-21 at 13 47 03](https://user-images.githubusercontent.com/17945926/191485332-bc9e0ebd-d0d1-4939-96b3-7faab8cb3575.png)

**Comment by hirsch88** [comment]
Will be done later

**Comment by joachimprinzbach** [comment]
Moved after GO Live, not a major issue. Feel free to contact me if you have questions.

**Comment by Gagne87** [comment]
As already mentioned I would use for this component our inverted buttons. As they are designed to only work on dark backgrounds we need also a dark background color. As the component should be functional and not too distracting I used grey-4. Let me know what you guys think. 

![Image](https://user-images.githubusercontent.com/29020214/196175907-c24d6b96-135c-47c7-b3d2-193ac3699bd5.png)

**Comment by madaluca** [comment]
there is another issue when the tabs are split in multi lines, the tabs haven't the same height. Can you include also the fix for this, please? @hirsch88 
![IMG_0013](https://user-images.githubusercontent.com/17945926/196422365-23bbb12f-7679-47ec-adae-a54eebf98179.png)
