### ISSUE TITLE
[bal-datepicker] - days on mobile view are not correctly aligned

### ISSUE THREAD

**Issue by mkasparsone** [baloise-incubator/design-system#606]
## Detailed description
As seen in the image - days don't align. This issue was first noticed on Chrome browser

![Screenshot 2022-09-22 at 16 18 35](https://user-images.githubusercontent.com/50512198/191758087-a0b6e654-eb2a-4552-aa70-da4c5764e0b4.png)

**Comment by hirsch88** [comment]
Duplicated issue [#580](https://github.com/baloise-incubator/design-system/issues/580)
