### ISSUE TITLE
[bal-radio] Min / Max widht for Radio Button

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#611]
### Example - Adjust to max widht
![Image](https://user-images.githubusercontent.com/62377419/191934003-1d67e562-377c-4133-93ef-59bb1e73fae9.png)

https://baloise-reb.qa.aperto.systems/baloise-qa/de/smoketest/form-page.html

`TBD - Mobile Full Widht option?`

### Example - Min width 
![Image](https://user-images.githubusercontent.com/62377419/191935090-a8ef54fa-5e1f-4675-be6a-0cb06da15e6b.png)

https://baloise-reb.qa.aperto.systems/fallback/docu/de/components/Formularbaukasten/Switch-Toggler.html

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/704
