### ISSUE TITLE
[bal-radio] - Angular: status touched not set

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#623]
The status "touched" is not returned correctly for the Bal-Radio components. 

I usually expected the form-control status "touched" to be set for reactive forms after clicking on the component and leaving it (after onBlur() event)

This works for bal-field, for example - furthermore, this also works for native radio elements, but not for the bal-radio.

![image](https://user-images.githubusercontent.com/292344/192334093-71fc8a26-e87c-4359-9136-ba0b642d484f.png)

attached is an example file (based on the example)

[scratch_155.ts.txt](https://github.com/baloise-incubator/design-system/files/9648067/scratch_155.ts.txt)

**Comment by nobilo** [comment]
@tklueber pls check with version [v10.24.1](https://github.com/baloise-incubator/design-system/releases/tag/v10.24.1)

**Comment by tklueber** [comment]
Sorry, I cannot confirm that the fix works. I tested the same example with 10.24.1 but the form controls do not get the status touched. 

Maybe it is not enough to bind only the onBlur event - perhaps a markOnTouched call is missing/needed?!
