### ISSUE TITLE
[bal-select-option] disabled doesn't work

### ISSUE THREAD

**Issue by Sreilys** [baloise-incubator/design-system#628]
## Detailed description

We are trying to reproduce the mobile design of the filters in the results page, and we use the select component, but the current implementation does not support the disabled style.

I expected the select option to be grey and in a disabled look.

This happens in all the browsers.

<img width="826" alt="Screenshot 2022-09-27 at 11 12 37" src="https://user-images.githubusercontent.com/8192292/192485641-ee561d8b-3719-4bc9-95f1-5fbdbe55146b.png">

**Comment by hirsch88** [comment]
@Sreilys Please use the placeholder for that case

**Comment by Gagne87** [comment]
@Sreilys can you please add a concrete use-case, so that we can better discuss rather this makes sense or not? Thanks a lot.

**Comment by Gagne87** [comment]
Decision by @Gagne87 @mladenplaninicic @Sreilys: On VPM and VPS only options are shown where the system returns them.
