### ISSUE TITLE
[bal-navbar] Partner Logo squeezed

### ISSUE THREAD

**Issue by GinaBiondo** [baloise-incubator/design-system#630]
## Detailed description

> the partner logo is squeezed on mobile viewports

<img width="334" alt="Bildschirmfoto 2022-09-27 um 11 31 27" src="https://user-images.githubusercontent.com/72393447/192490013-08873358-1ba4-483f-a3ae-4e0ae715262b.png">

**Comment by hirsch88** [comment]
@GinaBiondo-aperto is that already fixed by with you last PR's?

**Comment by GinaBiondo** [comment]
Yes, it is! :) Thought I added that to the PR but apparently missed it
