### ISSUE TITLE
[Pagination] - wrong button styles

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#635]
looks like the button is used as inverted

![image](https://user-images.githubusercontent.com/6384499/192528346-4106d398-e3f7-4c53-bb14-b720e25641f0.png)

Depending on #228

**Comment by hirsch88** [comment]
if you click the button it turns white

**Comment by hirsch88** [comment]
@Gagne87 & @clastzoo could you verify the design for those buttons

**Comment by Gagne87** [comment]
Depending on #228
