### ISSUE TITLE
Component with several collected questions

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#645]
We have a section where we ask various questions to the Insurance Taker which can answer each question with a yes or no.

![image](https://user-images.githubusercontent.com/292344/192758552-e0435bdf-9747-44d0-8ba5-313d846c61b3.png)

Visually we are not that happy with it. It is not obvious at first glance that for each question the user has to make a choice between the two variants yes and no.

Therefore we want to ask here if there is either a general component that is meant exactly for this use case or perhaps there is a more suitable solution that fits better for this use case.

We would be happy to cooperate to find a better solution in the person of Marco E. Petra or me, should this be desired.

**Comment by clastzoo** [comment]
Hi @tklueber  a  quick win would be to choose the normal radio button. Instead of the select button. They are visually more "balanced"

If you see the need for a total new interaction model we'd be super happy to collaborate after the go-live.

Let me know what you think about it.

**Comment by tklueber** [comment]
Thank you @clastzoo  very much for your input. Yes, we followed your suggestion and now we use normal radio buttons for the yes-no questions.

We would, however, still like to raise the question again after go-live, should we want / need a new solution. Then we would create a new request - for now, this Github request can be closed

thank you.
