### ISSUE TITLE
[Mobile-Application] Create Base Guidelines for Baloise Native Apps

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#648]
### Set basic values for native application

- [ ] App Icon Rules
- [ ] Splashscreen
- [ ] IOs / Android Store Screens

Draft
https://www.figma.com/file/w6bGlt9F7pTMwfgUFLTpAD/%F0%9F%94%B5-Brand-Assets?node-id=1560%3A3146&viewport=1929%2C1255%2C0.24

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/790
