### ISSUE TITLE
[Icon] Investiagtion about icon sizes

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#651]
![Image](https://user-images.githubusercontent.com/62377419/192828590-415ce58a-1fa6-4b5d-b9ae-565faa03f4b4.png)

https://ob-cmsauthor.balgroupit.com/baloise-ch/de/privatkunden/blog.html

**Comment by hirsch88** [comment]
![Image](https://user-images.githubusercontent.com/6384499/199691272-f8a7d5a0-3147-42df-8d59-d7a10a583cf3.png)
