### ISSUE TITLE
[Testing] Digital Brand Review for Baloise Application

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#656]
- Art KK Application
- Portal Application
- Galileo
- Household
- Legalprotection
- MF Admin
- Other Business Application

**Comment by clastzoo** [comment]
Dicuss with @christophgeering @joachimprinzbach

**Comment by hirsch88** [comment]
- brand layer
- technical layer
- functional layer

**Comment by hirsch88** [comment]
first do  the brand review. offer help to the teams

**Comment by hirsch88** [comment]
create a overview table with al the apps which are using the DS

**Comment by clastzoo** [comment]
https://confluence.baloisenet.com/atlassian/display/BALMATE/Rebrand+-+Internal+Application 

@Gagne87 i've created this draft, let's sit together on monday and analyse how we tackle this.

**Comment by christophgeering** [comment]
@clastzoo & @Gagne87: I have just added a few applications and a link to all ART KK applications. Definitely not finished, but a good start probably
