### ISSUE TITLE
[`bal-select`] break long option text to new line

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#659]
## Detailed description
On mobile if option text is too long then text is not fully visible.

## Additional information
![item cut off 2 (1)](https://user-images.githubusercontent.com/35540320/193056532-e86a8a5c-453e-41f8-a794-0452e5980a4c.png)

**Comment by Gagne87** [comment]
@Gagne87 try to reproduce on Storybook and then prioritise.

**Comment by Gagne87** [comment]
Hi guys @mladenplaninicic @nobilo @clastzoo, as discussed I tried to reproduce the reported bug and can confirm that we have a problem. In my opinion the text should wrap and the fly-out should have the same width than the field.
