### ISSUE TITLE
[bal-file-upload]: break long label text

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#661]
## Detailed description

If long text is used for `bal-file-upload` label, it won't break on mobile

## Additional information
<img width="369" alt="Screenshot 2022-09-29 at 23 02 35" src="https://user-images.githubusercontent.com/35540320/193134848-859a0652-b235-4b9c-aea1-7d010266e47a.png">

**Comment by Gagne87** [comment]
Also here: Text should wrap and be centered; height of the element should be flexible and set to auto.
