### ISSUE TITLE
[bal-datepicker] all dates not showing up

### ISSUE THREAD

**Issue by mkasparsone** [baloise-incubator/design-system#664]
## Detailed description

For some reason datepicker shows only a few days in February. Tested on v10.23.3

![Screenshot 2022-09-30 at 13 27 43](https://user-images.githubusercontent.com/50512198/193250928-c03d30c6-9591-4071-abf1-137afdd42de0.png)
![Screenshot 2022-09-30 at 13 31 31](https://user-images.githubusercontent.com/50512198/193251467-dde38781-1512-4152-b5a0-70183827b26a.png)

**Comment by Gagne87** [comment]
Try to reproduce and get back to Kasko.

**Comment by Gagne87** [comment]
@mkasparsone could you provide us with a detailed description how to reproduce this as well as some technical specs (device, browser, version etc.). Thanks a lot.

**Comment by mkasparsone** [comment]
@Gagne87 Hey! it seems that with the latest version this issue has disappeared. Will close the bug
