### ISSUE TITLE
[bal-navigation] [mobile] popover trigger has different hover effect than the rest of the buttons in the footer

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#665]
https://user-images.githubusercontent.com/17945926/193518401-f79cbc18-e699-4506-a3b1-a8f94f7da8a4.mov

https://design-system-next.vercel.app/?path=/story/components-navigation--basic

**Comment by mladenplaninicic** [comment]
buttons are changed, we don't need to do this.
