### ISSUE TITLE
[bal-snackbar] wrong width

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#667]
The snackbar width should be 440px on tablet and desktop, and 288px on mobile. 

https://design-system-next.vercel.app/iframe.html?args=duration:0&id=components-notice-snackbar--basic&viewMode=story

![Screenshot 2022-10-03 at 12 50 52](https://user-images.githubusercontent.com/17945926/193549214-c616a382-1acb-470e-b8e5-57c05fdb5058.png)

**Comment by Gagne87** [comment]
@mladenplaninicic checked the changes and is ok for me. Thanks!
