### ISSUE TITLE
Figma licensing

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#673]
Currently there is following problem with our licensing model and SSO: 

- Everybody who has access via SSO to Figma can change their permission to "editor"
- Admins don't have the right to see every project 

According to the Figma support this problems can be only handled by upgrading to the higher version of Figma "Enterprise", which would generate $10'000 more costs.

**Comment by christophgeering** [comment]
Setup meeting with Laurent, Andreas & Michael @christophgeering

**Comment by christophgeering** [comment]
Meeting on Friday, October 7th at 11 am
