### ISSUE TITLE
[bal-accordion] Links in an accordion are twice selected

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#679]
Due to the fact that items sit in an accordion, which as a whole component is hoverable, all items are automatically hovered.

![Image](https://user-images.githubusercontent.com/62377419/193848267-c870679c-693d-42e4-84e5-db16662cdab1.png)

**Live Example**
https://baloise-reb.dev.aperto.systems/baloise-qa/de/qa/berater_import.html

**Comment by hirsch88** [comment]
fixed
