### ISSUE TITLE
[bal-tabs] - vertical - title don't wrap in the next line

### ISSUE THREAD

**Issue by Sreilys** [baloise-incubator/design-system#688]
<img width="1173" alt="Screenshot 2022-10-06 at 09 57 29" src="https://user-images.githubusercontent.com/8192292/194268629-89046d95-a4a4-4ec2-96e5-5d189c81fabb.png">

**Comment by janineKleessen** [comment]
![tab_linewrap](https://user-images.githubusercontent.com/96522578/194503258-d0e25afa-6fa6-4078-836e-7a0269ff85e1.png)
This issue is reproducible in the DS, if the tabs are vertical the slider option should not be there and the text should wrap in the next line

**Comment by hirsch88** [comment]
lets wrap to the next line also verify for horizontal usage
