### ISSUE TITLE
[bal-datepicker] Mobile alignment of day names is off

### ISSUE THREAD

**Issue by JasperDeLanghe** [baloise-incubator/design-system#689]
## Detailed description

The day names in the bal-datepicker do not align with the actual days.
See screenshot below.

## Additional information

![Screenshot 2022-10-06 at 10 57 54](https://user-images.githubusercontent.com/25288931/194275845-48bc16db-53b6-40b4-837a-db3bd108c371.png)

**Comment by hirsch88** [comment]
Duplicated issue #580
