### ISSUE TITLE
[bal-tabs] Focused state current page

### ISSUE THREAD

**Issue by mladenplaninicic** [baloise-incubator/design-system#694]
![Image](https://user-images.githubusercontent.com/62377419/194309035-5524230d-242d-4857-a2ce-8eaf29948827.png)

![Image](https://user-images.githubusercontent.com/62377419/194309056-4867509d-28ff-45a8-83c7-9149c872c006.png)
https://baloise.de/de/ueber-uns.html

**Comment by Gagne87** [comment]
Bug: Missing active state for root pages.

**Comment by hirsch88** [comment]
@clastzoo & @Gagne87 just set the value where to start
