### ISSUE TITLE
[Product Slider][Mobile] Slider shows empty container

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#696]
Tested on: iPhone 12 mini, Safari, iOS 16.0.2

Steps to reproduce: 

1. Open product slider (Storybook) on your mobile device 
2. Drag slider all the way to the right 

>> Last container is empty (compare to screenshot)
>> Expected behaviour: Slider should stop at last container

![Image](https://user-images.githubusercontent.com/29020214/194492205-66ca9e4b-b91b-4599-8b4e-d404540b96b4.jpg)

**Comment by hirsch88** [comment]
takes to much effort, will be done later with a refactoring of all the sliders
