### ISSUE TITLE
Toast component close all method

### ISSUE THREAD

**Issue by stefanbukovski** [baloise-incubator/design-system#703]
### Summary

It would be nice to have the functionality to just call close() method and close all instances of toast component. 

For example if I want to close it from another file and another effect in store I would have done it like this: 

`this.toastService.close();`

But currently I need to put this in a constant first like this (and then closing cannot be done from another file or effect without additional implementation or wrapper service): 
```
const toast  = this.toastService.create({...});
toast.close();
```

Just development requested.

### Justification

Currently in premium calculators we have 3rd party library ngx-toastr and closing can be done programmatically. Use-case would be if the toast appears for some input error then if I correct it and successfully submit the contract, I want to clear the toast and not to have to do it manually.

**Comment by hirsch88** [comment]
@stefanbukovski just use `this.toastService.dismissAll()`

**Comment by stefanbukovski** [comment]
@hirsch88 I looked it up but did not find it in BalToastService. There is only create() method there. Am I missing something?
