### ISSUE TITLE
[bal-list-item-accordion-body] Initial max-height miscalculated when accordion contains yt video

### ISSUE THREAD

**Issue by fabio-tedesco** [baloise-incubator/design-system#704]
## Detailed description

As described here https://jira.ibmix.de/browse/BARE-959 the accordion item hasn't the right height in case it contains a video.

## Steps to reproduce the issue

1. Load the page https://baloise-reb.dev.aperto.systems/baloise-ch/de/private/test-accordions-playground.html f.e.
2. Accordion item containing the video hasn't the right height
3. Max-height on bal-list-item-accordion-body is set to 11px

## Additional information

![Testing_Accordion_Playground](https://user-images.githubusercontent.com/94684353/194569493-62f64719-2be6-422c-b0e6-532756fad140.png)

**Comment by hirsch88** [comment]
solutions

1. do not use lazy-loading
3. pass the height of the content through a prop
4. or listen to an event to know when the full size is ready/loaded

**Comment by hirsch88** [comment]
we will go if solution 3

**Comment by hirsch88** [comment]
@fabio-tedesco please provide us the event name of it

**Comment by fabio-tedesco** [comment]
@hirsch88 here is it 'readyIframe'
