### ISSUE TITLE
[bal-tabs] href not working anymore (on steps variant)

### ISSUE THREAD

**Issue by max-voss** [baloise-incubator/design-system#711]
## Detailed description

Tested as static form steps:
href on bal-tab-tems doesn't get correctly added to the generated a tag
Example:
`<bal-tab-item done label="Eventversicherung 1" href="/baloise-qa/de/qa/Sprints/sprint-19/Eventversicherung-1.html"></bal-tab-item>`

generates:
`<li class="bal-tabs__steps__item bal-tabs__steps__item--active bal-tabs__steps__item--done bal-tabs__steps__item--clickable data-test-tab-item" data-label="Eventversicherung 1" data-value="" data-index="0">
    <a class="bal-tabs__steps__item__button bal-tabs__steps__item__button--clickable"> ...`

**Comment by hirsch88** [comment]
@max-voss  because the steps should not be links
