### ISSUE TITLE
[bal-number-input] ValidityState patternMismatch caused by suffix

### ISSUE THREAD

**Issue by max-voss** [baloise-incubator/design-system#717]
## Detailed description

If you use a suffix like CHF or EUR in a number-field and try to validate it, you'll get a pattern mismatch since the value contains "CHF" but is validated against "numbers only" with [0-9]*

## Steps to reproduce the issue

1. Use number-input with Suffix
2. add value
3. check ValidityState per JS
4. patternMismatch

**Comment by hirsch88** [comment]
done with [10.24.8](https://github.com/baloise-incubator/design-system/compare/v10.24.7...v10.24.8)
