### ISSUE TITLE
Wait for fonts to be loaded in the bal-app

### ISSUE THREAD

**Issue by mladenplaninicic** [baloise-incubator/design-system#718]
cy.document()
      // https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/ready
      // The promise will only resolve once the document has completed loading fonts,
      // layout operations are completed, and no further font loads are needed.
      .then(document => document.fonts.ready)

**Comment by hirsch88** [comment]
discuss with ibm I x
