### ISSUE TITLE
[bal-card] app-type = agent. Tablet view not correct

### ISSUE THREAD

**Issue by Sreilys** [baloise-incubator/design-system#719]
## Detailed description

In Tablet view, the image and the info text should be next to eachother. 
At the moment is image on top and info text at the bottom

## Additional information

Links: https://baloise-reb.dev.aperto.systems/author/baloise-qa/de/qa/Sprints/Sprint-18/agent.html

Figma 
<img width="1303" alt="Screenshot 2022-10-11 at 11 42 40" src="https://user-images.githubusercontent.com/8192292/195057053-f513d5b3-3771-414e-af43-6b80e3c6b3e1.png">

Current to be fixed
<img width="938" alt="Screenshot 2022-10-11 at 11 46 20" src="https://user-images.githubusercontent.com/8192292/195057129-47d6f326-915d-4e46-b490-55d0524a92d3.png">

**Comment by hirsch88** [comment]
@Sreilys do you have a example page for us?

**Comment by Sreilys** [comment]
This issue has to do with missing implementation of type agent, not with DS. I will close it.
