### ISSUE TITLE
[bal-number-input] min/max not triggering rangeOverflow/rangeUnderflow

### ISSUE THREAD

**Issue by max-voss** [baloise-incubator/design-system#722]
## Detailed description

The min/max values of the number-inputs don't work (anymore?). Expected result would be rangeOverflow/rangeUnderflow ValidityStates, currently nothing happens.
Maybe related to the suffix-changes...

## Steps to reproduce the issue

1. use bal-number-input with min/max props.
2. try bigger/smaller number
3. check validityState via JS

-> ValidityState is okay, browser doesn't prevent the input of the bigger/smaller number.

**Comment by clastzoo** [comment]
@max-voss is not supported by number input please use bal-input with the type number.

cc @hirsch88
