### ISSUE TITLE
option to pass heading string/html to toast

### ISSUE THREAD

**Issue by stefanbukovski** [baloise-incubator/design-system#724]
### Summary

It would be nice if there would be another property in toast config object to pass heading string/html, besides the message option.
For example;
```
balToastController.create({
                heading: toastHeading,
                message: toastMessage,
                color: 'warning',
            });
```

Just development required.

### Justification

In DISA premium calculators there are different translations for heading text and for message text and some different logic applied to them so it would be handy if the toast would provide two different properties for this.

### Additional information

This first image would be from the old design and there you can see that we had different width and also "Connection problems" part of the text was provided to toast via heading property in the configuration.
The second image is the new implementation and there you can see that it looks maybe a bit stuffed (this was also one of the remarks in previous review). Heading was added via message property though but it would be nice to have separate heading property so that we could apply some logic to it.

![image](https://user-images.githubusercontent.com/108665216/195563781-82834510-ae41-472c-8cb3-31baf1bfbf0a.png)

![image](https://user-images.githubusercontent.com/108665216/195563318-6962142b-1e53-402a-a8f0-8430e40cf8f8.png)

**Comment by hirsch88** [comment]
@stefanbukovski by design toast do not have a heading. Could you send us an example?

**Comment by hirsch88** [comment]
Use the snackbar or use html with the message prop like in storybook

![Image](https://user-images.githubusercontent.com/6384499/195614753-70acd697-0a2f-489c-ba1c-6332b015b754.png)
