### ISSUE TITLE
option to control toast size

### ISSUE THREAD

**Issue by stefanbukovski** [baloise-incubator/design-system#727]
Summary
It would be nice if there would be an option in the component api to control the size of the toast (width for example).

Development and design required.

Justification
In some cases the toast can look stuffed with content (with fixed width as it  is now), for example if there is a lot of text in it and also if some html is provided in the message property. It may be a good idea to control the width for example if there is a lot of content inside.

### Additional information

This first image would be from the old design and there you can see that we had different width and also "Connection problems" part of the text was provided to toast via heading property in the configuration.
The second image is the new implementation and there you can see that it looks maybe a bit stuffed (this was also one of the remarks in previous review). Heading was added via message property though but it would be nice to have separate heading property so that we could apply some logic to it.

![image](https://user-images.githubusercontent.com/108665216/195563781-82834510-ae41-472c-8cb3-31baf1bfbf0a.png)

![image](https://user-images.githubusercontent.com/108665216/195563318-6962142b-1e53-402a-a8f0-8430e40cf8f8.png)

**Comment by hirsch88** [comment]
@stefanbukovski can you show us an example?

**Comment by hirsch88** [comment]
was fixed with 10.22.1

https://github.com/baloise-incubator/design-system/commit/d04f3a557c43a2e2d17f5a5c2a2a14a67d530612
