### ISSUE TITLE
[bal-button] - performance update

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#733]
only add the bal-spinner if loading is true to the DOM. to avoid adding to much html and keep the animation Lottie out of it

**Comment by hirsch88** [comment]
@max-voss @rainerblumenthal first performance improvment ;-)

**Comment by hirsch88** [comment]
![Image](https://user-images.githubusercontent.com/6384499/195560980-65690c3f-eeaa-42cf-a155-80ef8dba10ca.png)



![Image](https://user-images.githubusercontent.com/6384499/195561035-772bdd4f-6230-465e-a89b-97ca0ea1a302.png)

**Comment by hirsch88** [comment]
tested with https://design-system-next.vercel.app/iframe.html?args=logoAnimated:false&id=components-navigation--basic&viewMode=story

**Comment by hirsch88** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/6384499/195579565-85ff794c-952e-46fb-ac77-a125e3e2f22e.png">

with the spinner / Lottie fix

**Comment by hirsch88** [comment]
```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <style>
      .bal-body {
        display: none;
      }
    </style>

    <script type="module" src="/build/design-system-next-components.esm.js"></script>
    <script nomodule src="/build/design-system-next-components.js"></script>
  </head>
  <body>
    <bal-doc-app class="bal-body">
      <main class="container py-5">
        <bal-button>Button</bal-button>
      </main>
    </bal-doc-app>
  </body>
</html>

```

**Comment by hirsch88** [comment]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/6384499/195580385-105f8f98-313e-4fa4-891d-dbf1b559a651.png">

**Comment by hirsch88** [comment]
on mobile we had 93

<img width="825" alt="image" src="https://user-images.githubusercontent.com/6384499/195580795-cb72baf5-1812-4a77-80aa-d6ef284cd6e3.png">

**Comment by hirsch88** [comment]
without Lottie

<img width="821" alt="image" src="https://user-images.githubusercontent.com/6384499/195581448-eedeaaf0-e6ee-42ad-8939-07c335039b81.png">

**Comment by hirsch88** [comment]
without the svg icons

<img width="812" alt="image" src="https://user-images.githubusercontent.com/6384499/195582007-014062c4-a103-49e1-826b-8bebc6cf4a8e.png">

**Comment by rainerblumenthal** [comment]
I really like having before / after screenshots :) Thank you.
