### ISSUE TITLE
Enable mark of selected language in bal-footer

### ISSUE THREAD

**Issue by nobilo** [baloise-incubator/design-system#734]
### Mark currently selected language in `bal-footer`

Enable marking selected language in bal-footer, do we want to enable it ?

### Available extra resources

In old dashboards selected language was marked like this:
![image](https://user-images.githubusercontent.com/11984467/195564757-01e13aab-3bfe-4980-a2c0-c4b9f5af9cd2.png)

currently it is like this:
![image](https://user-images.githubusercontent.com/11984467/195565083-7a2fab53-6546-4ce6-b023-d597edc1cd26.png)

_Baloise Desing System is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by clastzoo** [comment]
Design a selected / active state for language. @clastzoo

**Comment by hirsch88** [comment]
done in the new footer style with the dropdown
