### ISSUE TITLE
toast - set maximum number of opened instances

### ISSUE THREAD

**Issue by stefanbukovski** [baloise-incubator/design-system#753]
### Summary

It would be nice if there would be an option in the component api to set the number of maximum opened instances.
For example if I trigger one success toast and then some time after I trigger another warning toast, then the first one should be overridden and toasts should not be stacked one after another on the screen. So if I set that config property to 1 for example then only one toast should be displayed on the screen, no matter how many of them I trigger.

Development required.

### Justification

This was the behaviour in our premium calculators so far (we used 3rd party library for this ngx-toastr and there we were able to set the maxOpened config property to 1 for example).

**Comment by Gagne87** [comment]
@Gagne87 will talk to @stefanbukovski

**Comment by Gagne87** [comment]
@stefanbukovski in my opinion the toasts should be stacked. Usually there is very valuable information in those toasts, eventually they are even dependant on each other. So I would suggest to leave it as it is. Let's have a discussion about this.
