### ISSUE TITLE
[bal-nav] Design active state for deeper links in the navigation

### ISSUE THREAD

**Issue by mladenplaninicic** [baloise-incubator/design-system#760]
- [ ] Design an active link-state in Figma

🕹️ Prototype:

https://www.figma.com/proto/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?page-id=187%3A2287&node-id=2711%3A18525&viewport=1871%2C541%2C0.11&scaling=min-zoom&starting-point-node-id=2711%3A18525&show-proto-sidebar=1

https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=42309%3A351617&viewport=16528%2C685%2C1.47

Propsal
![Image](https://user-images.githubusercontent.com/62377419/197560375-fff937bd-4538-4a91-9293-c4753f286380.png)

**Comment by Gagne87** [comment]
@clastzoo creates another ticket.

**Comment by clastzoo** [comment]
https://jira.ibmix.de/browse/BARE-1035
https://jira.ibmix.de/browse/BARE-1036

Tickets are created on IBM's side.

**Comment by clastzoo** [comment]
Swapped this ticket to a design task
