### ISSUE TITLE
[bal-datepicker] Datepicker UI breaks upon changing year & month

### ISSUE THREAD

**Issue by dstab** [baloise-incubator/design-system#761]
## Detailed description
The described issue happens for some of the edge cases. Once we choose a date which days or months are outside one of the validation bounds then the date picker UI breaks.
In the situation described in the vid, the validations are `min`: `18.10.1992`, `max`: `17.10.2022`. If we choose a date like `01.01.2020`, later changing the year to 1992 will result in the date being out of validation bounds. The date will be `01.01.1992` and this is where the issues start to appear.

## Additional information
[Untitled_ Oct 17, 2022 5_26 PM.webm](https://user-images.githubusercontent.com/107861285/196296315-065e2f65-d62d-40cd-85fb-8a0acd1d9ee5.webm)

**Comment by mladenplaninicic** [comment]
will be done in #207
