### ISSUE TITLE
[quick-start-widget] Design proper global hover state

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#763]
Currently there is no interaction state developed on the.

![Image](https://user-images.githubusercontent.com/62377419/196354132-bea56297-0dba-44da-aa12-01b7012ccd2d.png)

Create:

- [ ] Hover State
- [ ] Active State

**Comment by clastzoo** [comment]
@hirsch88 how could we tokenize for example, a card hover for a global use? Otherwise this component has a individual hover?

**Comment by hirsch88** [comment]
https://baloise-design-system.vercel.app/?path=/docs/components-card--basic#card-variations

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/788
