### ISSUE TITLE
[bal-select]: selected value displayed differently on iOS and Android 

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#766]
## Detailed description

Selected value displayed differently on iOS and Android.

## Additional information
iOS
![img_4397](https://user-images.githubusercontent.com/35540320/196389645-0454d63b-5238-43db-8dad-4bf4fe9ad95d.png)
Android
![signal-2022-10-17-134619](https://user-images.githubusercontent.com/35540320/196389770-78b46156-94ea-47d4-8fe1-043c16e4dc9f.png)

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/703
