### ISSUE TITLE
NaN issue with bal-number-input

### ISSUE THREAD

**Issue by JelenaSretenovic** [baloise-incubator/design-system#768]
Focus on <bal-number-input> component displays NaN text.
It's removed after we start typing and works properly, but initial NaN shouldn't be displayed

**Comment by hirsch88** [comment]
@JelenaSretenovic could you give us your markup? you html template, which props you used and with what version did you have that issue?

can you reproduce it in storybook?

**Comment by JelenaSretenovic** [comment]
Hi @hirsch88 , I explained it to @nobilo 
I could reproduce it also in design-system-examples on this branch https://github.com/baloise/design-system-examples/tree/feat/angular-v14-next
I just used `bal-number-input`  with 'decimal' property:
```
  <bal-field>
    <bal-field-control>
      <bal-number-input formControlName="test" decimal="2"></bal-number-input>
    </bal-field-control>
  </bal-field>
```
And for initial value for control test I tried to use `null`, `empty string `or `undefined `but for all cases I get NaN text when I click on input.

**Comment by Gagne87** [comment]
@nobilo will retest this one after the release tomorrow.
