### ISSUE TITLE
[Elevation] Disucss how we can bring shadow tokens to the DS

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#774]
Due to the fact of a lack on a card interaction we pumped in to missing elevations / shadows.
We might combine this with the Z-Index topic to align properly.

Examples
https://www.duetds.com/tokens/#box-shadow
https://tailwindcss.com/docs/box-shadow

In the current DS we have a `Default` and a `Large` shadow

**Comment by Gagne87** [comment]
@clastzoo will make a design proposal
