### ISSUE TITLE
[bal-navigation] - refactoring - old

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#780]
**Plan**

- [ ] Create ScrollUtil to disable scrolling on elements with JS
- [ ] Enable popover work with select and date picker @mladenplaninicic 
- [ ] Design active link state @clastzoo 
- [ ] Design mobile list with or without line @clastzoo 
- [ ] 

Due to performance issues we need to change how the component gets rendered. 
Goal is that not mobile is not added to the DOM when desktop is used and the other way around.
Moreover, we need to use more functional components to improve the rendering.

![Image](https://user-images.githubusercontent.com/6384499/196690024-d9163552-0270-41af-ba38-c6dce3fa92f4.png)

Linked issues:

- #771 
- #694 
- #736 
- #941
- #1132

### Breakpoint Gap

- [ ] Fix breakpoint issue

From: 
1401px → 1439px the menubar is not attached to left and right. 

![Image](https://user-images.githubusercontent.com/62377419/197467920-cd9751c7-330a-4168-83e6-0853b00cb0fc.png)
![Image](https://user-images.githubusercontent.com/62377419/197467921-d8907fd1-1963-4f94-b4ee-2bb73f77760d.png)

### Active State for tab element in the navigation bar
- [ ] Implement active state for tab elements

![Image](https://user-images.githubusercontent.com/62377419/197559713-389de9fb-ec75-4769-b7a2-185fdccdeb74.png)

### Active State for deeper nested links in the navigation flyout
- [ ] Design an active link-state in Figma (Design Task #760 
- [ ] Implement link active states in the flyout menu

🕹️ Prototype:

https://www.figma.com/proto/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?page-id=187%3A2287&node-id=2711%3A18525&viewport=1871%2C541%2C0.11&scaling=min-zoom&starting-point-node-id=2711%3A18525&show-proto-sidebar=1

### **Acceptance Criteria IBM iX:**

* SEO
  * titles should not have h-tag, because there are rendered before the first h1
  * Navigation points on mobile should not be rendered (also accessability )
  * Do not render all children pages in the navigation - as this eats up alle the link juice
it is better only to render the children of the currently active page in the navigation  
  * it is better only to render the children of the currently active page in the navigation 
 
* Accessibility
  * Links should be underline if the user are on the same page

* Visibility for the user in which area he is navigating (see subtasks)
* Navigation should be sticky on mobile or slides in if the user srcoll to top (Should be discussed)
* MetanavigationLink should be hidden if there is only one see [BARE-1352](https://jira.ibmix.de/browse/BARE-1352)
   * on mobile should be the accordion one level higher, so the user don't has to open only one accordion

**Comment by clastzoo** [comment]
Please always double check the ticket from the IBM iX board regarding requirements and inputs.
https://jira.ibmix.de/browse/BARE-1261
