### ISSUE TITLE
[bal-product-slider] Improve the slider on touch devices

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#785]
The swipe gesture doesn't feel smooth, if the user swipes, he also triggers the hover effect on an ipad device. 

- [ ] Improve Slider

https://user-images.githubusercontent.com/62377419/196877179-6ac62259-5821-40cb-b7d7-42ff39a0495e.mp4

**Comment by Gagne87** [comment]
Retest when IBM has rolled out the new release. Test in Storybook -> close

**Comment by Gagne87** [comment]
@mladenplaninicic could you send a link to @clastzoo where he can test? Thanks.
