### ISSUE TITLE
VisualLevel for list title

### ISSUE THREAD

**Issue by janineKleessen** [baloise-incubator/design-system#787]
For the title (bal-list-item-title) in footerlist we need the option to set a visualLevel, because currently the level is h5 and we need a displaysize of h2.

https://design-system-next.vercel.app/?path=/docs/components-list--basic#component-api

see Figma https://www.figma.com/file/TpLyniy71JAMZhps0qHhVU/Baloise-%E2%80%93-UI-Kit-(Team-Library)?node-id=4078%3A44407

**Comment by nobilo** [comment]
copy from bal-heading :)
