### ISSUE TITLE
Fields in background are still selectable if modal dialog is shown

### ISSUE THREAD

**Issue by baengel** [baloise-incubator/design-system#803]
## Detailed description

> If you are opening a modal dialog, the button or fields in the background are still selectable with the tab key.

> the fields in the background shouldn't be selectable.

> chrome

## Steps to reproduce the issue

1. go to https://baloise-design.vercel.app/?path=/story/components-notice-modal--with-input
2. click on "Trigger a modal" button
3. If you go with tab trough fields (or shift + tab) then you can still select the button in the background

## Additional information
![image](https://user-images.githubusercontent.com/12473997/197535168-a867f15d-1f0c-44a4-b9b9-056087c35878.png)

in mybaloise-business it's possible to open the same dialog several times.

Will be fixed with #131

**Comment by Gagne87** [comment]
Hi @baengel this bug is already known and will be fixed with #131 . I would close this issue. Ok for you?
