### ISSUE TITLE
Issues with pagination component

### ISSUE THREAD

**Issue by baengel** [baloise-incubator/design-system#816]
The pagination:
![image](https://user-images.githubusercontent.com/12473997/197809121-2f4e19aa-ddb4-4cd3-a9d5-483cf7717118.png)
should be "< 1 2 ... 5 >" not <1 ... 2 ... 5>. 
Same at the end: 
![image](https://user-images.githubusercontent.com/12473997/197809335-194a08b4-0fbd-487d-8e70-9736936bfe09.png)
should be "< 1 ... 4 5 >" not "<1 ... 4 ... 5 >"

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/706
