### ISSUE TITLE
Fix Actions in StoryBook

### ISSUE THREAD

**Issue by mladenplaninicic** [baloise-incubator/design-system#821]
Actions in Snackbar are not working. Check also other components.

Components:

- [ ] Accordion
- [ ]  App
- [ ] Badge
- [ ] Button
- [ ] Card
- [ ] Close
- [ ] Data
- [ ] Heading
- [ ] Hint
- [ ] Icon
- [ ] Image Slider
- [ ] List
- [ ] Logo
- [ ] Navbar
- [ ] (Navigation)
- [ ] Pagination
- [ ] Product Slider
- [ ] Shape
- [ ] Stage
- [ ] Table
- [ ] Tabs
- [ ] Tabs Steps
- [ ] Tag
- [ ] Text
- [ ] Checkbox
- [ ] Radio
- [ ] Datepicker
- [ ] Field
- [ ] FileUpload
- [ ] Input Stepper
- [ ] Input
- [ ] Number Input
- [ ] Select
- [ ] Slider
- [ ] Textarea
- [ ] Time Input
- [ ] Notification
- [ ] Toast
- [ ] Snackbar
- [ ] Modal
- [ ] Sheet
- [ ] Footer
- [ ] Form
- [ ] Form Grid
- [ ] Input Group
- [ ] Notice
- [ ] Popover
- [ ] Spinner

**Comment by hirsch88** [comment]
done
