### ISSUE TITLE
implement property "inverted" for bal-radio

### ISSUE THREAD

**Issue by fynnhaeny** [baloise-incubator/design-system#830]

**Comment by Gagne87** [comment]
@fynnhaeny could you please add a use-case to this ticket? At the moment we did not plan to have any inverted styles for form elements.

**Comment by fynnhaeny** [comment]
![image](https://user-images.githubusercontent.com/107040498/198987061-d52216e5-03d7-47fb-8466-973c677bda09.png)
In this picture you can see a "bal-radio". The color of the selection points are dark blue and should also be white. As a user you can recognize it better this way.

Like this:
![image](https://user-images.githubusercontent.com/107040498/198987687-b3d44a34-48ca-4890-a025-148aa59c1ab4.png)

**Comment by Gagne87** [comment]
@fynnhaeny we would need like the whole picture in order to be able to judge if this cannot replaced by an element that we already have in the library. Thanks for adding.

**Comment by fynnhaeny** [comment]
![image](https://user-images.githubusercontent.com/107040498/199663734-54156a08-8507-4622-9040-793017660748.png)
So, this is what the whole page looks like. The red marked one is a bal-radio. As you can see, "All" is selected and you can theoretically select the other continents. But as a user you can't see that so well. Is it possible to make the radio button also white, so that you can see it better?
P.S. The project ist called "Havarie Kommissare". This problem is not necessarily urgent but should be finished before the Frozen Zone.
Test URL: https://test-www.baloise.ch/havarie-kommissare/
