### ISSUE TITLE
provide baloise "brand-icons"

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#839]
Does it make sense to offer a library in the design system that makes all "brand-icons" available, which provides access to the SVGs in a similar way to the bal-icon component? (I mean this images: https://brand.baloise.com/document/10)

- Maybe the SVGs are not open source and a second internal repo should be created for them!?
- with svg-to-ts https://www.npmjs.com/package/svg-to-ts could simplify to create this and is also tree-shakeable
- is there perhaps already a simple approach or use case how to use these svg's ( except that you can download the svgs and insert them manually in the project)?

**Comment by Gagne87** [comment]
@tklueber possible in theory, but for several reasons we would like to connect it directly to the DAM. So the decision for that will take a while. We'll let you know about the outcome. For the moment just use the SVGs.

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/791
