### ISSUE TITLE
Modal is not modal

### ISSUE THREAD

**Issue by baengel** [baloise-incubator/design-system#854]
## Detailed description

> If I open a modal dialog, the background elements are still selectable (and clickable).
> open modal, and click on tab key to navigate. background elements will be selected.

![image](https://user-images.githubusercontent.com/12473997/199952673-02325d39-0f2e-46ea-a0b8-5b5189dfa4e5.png)

## Steps to reproduce the issue

1. Go to https://baloise-design.vercel.app/?path=/story/components-notice-modal--basic
2. open modal dialog with button 'Trigger a Modal'
3. Click on 'shift' key (or navigate with tab-key)
4. button in the background will be selected.

## Additional information

- in our application mybaloise dashboard, we can open a second, third, etc dialog.

**Comment by mladenplaninicic** [comment]
@baengel this one is already reported. Issue -> #131
