### ISSUE TITLE
Add clear function for form controls

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#856]
As user, I want to be able to delete my input in the search field with one click, so that I save time on deleting every single character. See example attached to this ticket. 

Acceptance criteria: 

- [ ] Find a way to place a button/icon in input fields in order that the user can delete inputs in a bulk
- [ ] Implement solution

![Image](https://user-images.githubusercontent.com/29020214/199977223-946b3bbf-a816-4ef0-87b3-4de8fc881489.png)

**Comment by hirsch88** [comment]
- [ ] date picker
- [ ] select / typeahead
- [ ] input
- [ ] number input

**Comment by hirsch88** [comment]
Do we reset to the initial value like a form reset or just to an empty value?

**Comment by Gagne87** [comment]
@hirsch88 can you check my example? For the other question I would say we do a form reset or do you have use-cases in mind where this would not work. 

[Components with.pdf](https://github.com/baloise-incubator/design-system/files/9952771/Components.with.pdf)

**Comment by Gagne87** [comment]
Figma example can be found [here](https://www.figma.com/file/lgDn2QZqoJJlYzGTe6cOmr/%F0%9F%A7%A9-Components?node-id=1696%3A9575)

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/698
