### ISSUE TITLE
[Fallback] Adjust browser support list in script

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#861]
![Image](https://user-images.githubusercontent.com/62377419/200304965-61553b8d-78c3-4f16-8659-10bf7d872824.png)

**Include to the script:**
- Safari - 10.XX - 13.XX

TBD - Safari 14. (Roughly 75000 User a year)

`If we take the list for granted V.14 - V.16 has to be supported`

**Script:**
https://github.com/baloise/web-app-utils/tree/master/packages/unsupported-browsers

**Documentation:**
https://confluence.ibmix.de/pages/viewpage.action?pageId=387012296

**Comment by clastzoo** [comment]
@clastzoo is gathering information within the digi team to get a clear answer on the supported browser list.

**Comment by clastzoo** [comment]
Safari 10 - 13 (None of those versions are showing up content)

![Image](https://user-images.githubusercontent.com/62377419/200584123-bbb40a63-bf50-4c95-a108-46788daddba4.png)

**Comment by clastzoo** [comment]
https://user-images.githubusercontent.com/62377419/200584125-23766a6c-2a18-473e-a8cd-767538a6aee5.mov

**Comment by clastzoo** [comment]
![Image](https://user-images.githubusercontent.com/62377419/200867803-7b9d0ad8-08c0-4e67-aab2-10047d2643aa.png)

We need to bring this up asap 🚀

**Comment by hirsch88** [comment]
@clastzoo add script to magnolia header
