### ISSUE TITLE
BalAutoFocus not always working

### ISSUE THREAD

**Issue by nobilo** [baloise-incubator/design-system#863]
We had to create our directive `cipFocus ` as default did not work, maybe we can improve. AutoFocus does not work on text-area, check dashbordE. 
/user-overlay-form/user-overlay-form.component.html and mybaloise-ui-lib/pull-requests/93/

**Comment by hirsch88** [comment]
We need to check if the element supports the setFocus() method.

**Comment by hirsch88** [comment]
```
import { AfterViewChecked, Directive, ElementRef } from '@angular/core'
import { deepReady } from '@baloise/design-system-components'

@Directive({
  selector: '[balAutoFocus]',
})
export class BalAutoFocus implements AfterViewChecked {
  constructor(private elementRef: ElementRef) {}

  ngAfterViewChecked() {
    this.setFocus()
  }

  async setFocus() {
    const el = this.elementRef.nativeElement
    if (el) {
      if (el.setFocus) {
        await deepReady(el)
        this.elementRef.nativeElement.setFocus()
      } else {
        this.elementRef.nativeElement.focus()
      }
    }
  }
}

```

**Comment by hirsch88** [comment]
packages/components-angular/src/focus.directive.ts

**Comment by hirsch88** [comment]
lets add a setFocus doc example in the form docs
https://baloise-design-system.vercel.app/?path=/story/implementation-form--page
