### ISSUE TITLE
Why bal-tag does not have white space breaks?

### ISSUE THREAD

**Issue by m4rc0z** [baloise-incubator/design-system#869]
I am wondering if there is a reason, that the bal-tag does not break when the text inside is too big for the screen. see screenshot:

![image](https://user-images.githubusercontent.com/20516386/200610398-c28902d6-7231-4d16-a816-e1d97ce17514.png)

**Comment by hirsch88** [comment]
add new prop multi-lines which removes the max height and breaks.

if possible lets add ellipsis in the default when it goes out of the viewport

**Comment by hirsch88** [comment]
@m4rc0z I tested it with the newest version and it worked.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/6384499/202437652-e55b6a99-8c13-45f1-b348-566274da2c97.png">
