### ISSUE TITLE
[bal-upload]: duplicate file message not displaying

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#871]
## Detailed description
Event `balRejectedFile` is not fired when adding one file and the same file right after that. It works if 2 files are added when adding one duplicate of those two files.

## Additional information

![file-upload](https://user-images.githubusercontent.com/35540320/201054132-fab02c67-fa54-47bd-83da-47b90d2d68eb.gif)

**Comment by hirsch88** [comment]
@BerSteve thanks for reporting we will have a look at this.
