### ISSUE TITLE
support autofill

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#873]
In the old application without design system we could use the browser functionality **autofill**. There, the user has the option of automatically entering addresses and names stored in the browser into the form fields. 

![autofill](https://user-images.githubusercontent.com/292344/201301111-4648f5cc-614a-46ac-b453-98844c9e80af.gif)

This is no longer supported by the DS. 

Is there a way to enable this again with the design system?

**Comment by hirsch88** [comment]
@mladenplaninicic @hirsch88 lets create a autofill form story

**Comment by hirsch88** [comment]
1. create a basic html form autofill example like in the screenshot above
2. create a second story with the same form but with the DS
