### ISSUE TITLE
[sass]: Don't use tilde in sass imports

### ISSUE THREAD

**Issue by dweber019** [baloise-incubator/design-system#895]
## Detailed description

Remove the tilde (`~`) sass imports.
Here an example https://github.com/baloise-incubator/design-system/blob/next/packages/css/scss/baloise-design-system.utilities.sass#L3.

The tilde imports are webpack or rollup specific and should not be used. Else tools like https://www.npmjs.com/package/sass can't be used anymore as they don't support this. In addition this is also deprecated by the https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules.

**Comment by clastzoo** [comment]
https://github.com/baloise-incubator/design-system/pull/892#pullrequestreview-1191653458
