### ISSUE TITLE
[button]: Primary button shows loading spinner twice when changing other attributes

### ISSUE THREAD

**Issue by dweber019** [baloise-incubator/design-system#897]
## Detailed description

The loading spinner (baloise logo) is shown twice, at least for the primary button.

<img width="330" alt="2022-11-21 17_53_52-Log in to Baloise" src="https://user-images.githubusercontent.com/1021324/203113880-948a3066-42d5-4d98-bc4c-68c07a5e0cdc.png">

I think this is caused by the following modification:
```
element.addEventListener("click", function () {
          element.loading = "true";
          setTimeout(function () {
            element.disabled = "true";
          }, 100);
        });
```

It seams that if `element.disabled = "true";` is executed, that an additional spinner is added.
If I toggle `disabled` on the button it will even add more spinners.

<img width="318" alt="2022-11-21 17_56_24-Log in to Baloise" src="https://user-images.githubusercontent.com/1021324/203114436-9eaf7c26-2591-4635-8537-2641e80971b4.png">

I think it has something to do with the `color` as `primary, danger, success, warning` have the issue but the other button colors not.

<img width="306" alt="2022-11-21 18_09_58-Log in to Baloise" src="https://user-images.githubusercontent.com/1021324/203117765-35290248-cb57-4b8e-b656-e9365fd5b3e5.png">
<img width="318" alt="2022-11-21 18_10_57-Log in to Baloise" src="https://user-images.githubusercontent.com/1021324/203117875-4e0e2da3-4258-4b79-9ce0-3731f2032bd6.png">

**Comment by hirsch88** [comment]
will be done with [#998](https://github.com/baloise-incubator/design-system/issues/998)
