### ISSUE TITLE
Have description(value) of each step in the input slider

### ISSUE THREAD

**Issue by aMiladinovic** [baloise-incubator/design-system#902]
### Summary

We want to use input slider with labels for each step (value) in the slider.

### Justification

If the steps between the beginning and the end are not clear we should be able to describe each step. Like in the proposed design: 
![image](https://user-images.githubusercontent.com/40214670/203546047-61c717d8-bf79-4cc4-8bae-b6bda3ad5436.png)

### Desired UX and success metrics

Currently there is no possibility to add labels, just the steps(ticks) without the description. There should be a prop which we can use to add a list of values which should be used as steps

### Must-have functionality

That we can provide the values which are displayed in the slider.

### Specific timeline issues / requests

It would be nice to have it by the end of this PI.

**Comment by hirsch88** [comment]
@clastzoo what is the state here?

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/716
