### ISSUE TITLE
Hint component icon broken into single row

### ISSUE THREAD

**Issue by jacnguymesoneer** [baloise-incubator/design-system#904]
## Description

During implementation of the Baloise Design System, we discovered that in case the label is too long and it makes use of the hint component, then the icon (i) is broken into a single row. This issue only happens when the label is too long and cannot make it into a single row. Therefore, the hint-icon (i) is currently standing alone in a third row, even though the second row still have enough space for the icon to be displayed.

## Pictures for reference

<img width="738" alt="image" src="https://user-images.githubusercontent.com/104895699/203694781-6f87208c-ca45-4d39-94e3-d328d31e7e05.png">

<img width="738" alt="image" src="https://user-images.githubusercontent.com/104895699/203695153-e6caad61-5d81-482d-b083-e474ae1e8af9.png">

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/715
