### ISSUE TITLE
Expanded cannot be used in combination with bal-button-group

### ISSUE THREAD

**Issue by jacnguymesoneer** [baloise-incubator/design-system#905]
## Description

Somehow the option expanded cannot be used in combination with bal-button-group. We wanted to use expanded to make the buttons width consistent, so that the button Cancel shares the same width as Next. 

After applying the expanded in bal-button-group, the buttons are outside the dialogue:

 ```
 <bal-button-group position="right">
    <bal-button color="info" (click)="onClose()" expanded>Cancel</bal-button>
    <bal-button color="primary" (click)="onSendSMSCode()" expanded>Next</bal-button>
  </bal-button-group>
```

<img width="842" alt="image" src="https://user-images.githubusercontent.com/104895699/203695759-327a335a-a4d0-4b78-bcef-9dbc6aed8162.png">

**Comment by hirsch88** [comment]
@jacnguymesoneer please do not combine positions and expanded ;-)
expanded means 100% of the with and the position does not make sense.
