### ISSUE TITLE
[link-list] Design active state for link list

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#907]
Active Link (Meta wise = Focus) property is available in storybook but not styled. 

![Image](https://user-images.githubusercontent.com/62377419/203940933-012296ee-23b3-4da0-b420-6de600152a68.png)

**Comment by clastzoo** [comment]
Mladen mentioned to wait till Gery is back to clarify this issue.

Question – should we stick with this?



![Image](https://user-images.githubusercontent.com/62377419/203941290-ffc21ad3-b345-458e-bb61-743aae6c5874.png)

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/795
