### ISSUE TITLE
Datepicker: Order wrong for balChange and balBlur

### ISSUE THREAD

**Issue by jacnguymesoneer** [baloise-incubator/design-system#913]
## Datepicker/Input field: Wrong order balChange and balBlur
During applying the new library, the development team discovered an issue related to the datepicker / input field

## Detailed description

```
current behavior (order):
	balBlur (x2) -> balChange
expected behavior (order):
	balChange -> balBlur
```

![date-picker](https://user-images.githubusercontent.com/104895699/204463373-99523e8f-e07d-443b-9af9-6adb03202394.gif)

In combination with the balBlur (2x), the issue also happens that the calendar will have a few milliseconds showing the flickering below:
![datepicker issue](https://user-images.githubusercontent.com/104895699/204471455-362e1de8-22aa-467b-8bc8-4b7570ca01b2.gif)

**Comment by hirsch88** [comment]
will be done by [#207](https://github.com/baloise-incubator/design-system/issues/207)
