### ISSUE TITLE
Various Cypress/DS Issues

### ISSUE THREAD

**Issue by svene** [baloise-incubator/design-system#916]
As discussed with @hirsch88 (feel free to split this up into several individual issues):

1. In the Cypress GUI elements appear twice. I think it does not have an influence on the test runs/results but it is very confusing during development. It would be nice if there is a way to prevent that.

2. Improve testing library: sometimes the API is not sufficient. Example: stepper (bal-tabs). We need a 'stepShouldNotBeActive(idx)' API for example to check that a stepper step is not active. Since there is not for this (see https://github.com/baloise-incubator/design-system/blob/next/packages/testing/src/commands/custom/bal-tabs.command.ts)
we did it like this: this.balTabsFindItem(idx).should('not.have.class', `bal-tabs__steps__item--active`);
But we prefer let the apps be decoupled of the DS internals. So I think the missing APIs should be added (preferred solution) or the selectors are exposed as constants to the apps. 

3. Introduce a global flag to turn off animations which might be a cause for flaky webtests.

4. When data is loaded into the form-group of our application for bal-selects the form-value temporily is set to 'null' (and afterwards back to the desired value). This temporary null value causes the form to become unpristine, which has the effect that the app thinks that the user has changed data of the form and then behaves differently. We think that this behavior is caused by the DS but are not 100% sure.

**Comment by hirsch88** [comment]
1. This is a known bug by cypress with web-components
2. we will have a look at that
3. already done
4. should also be done
