### ISSUE TITLE
Select Button Design Issues

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#918]
with multi-line labels in a select button (<bal-radio-group interface="select-button" ... ) the circle indicator is not shown in the middle. Also, in a group of radio buttons, the height should align with the highest element (i.e. expand the smaller ones).

![image](https://user-images.githubusercontent.com/292344/204571922-04c66442-616b-4d70-88e4-45a9a819b348.png)

As a workaround, we overwrite the styling in our app with the following attributes. (As a help)
```
::ng-deep {
  .package-selection {
    .bal-radio-checkbox {
      min-height: 4rem;
    }

    .bal-radio-checkbox__label::before, .bal-radio-checkbox__label::after {
      top: inherit;
    }
  }
}
```

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/705
