### ISSUE TITLE
Alignment Brand Assets Favicons

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#929]
- [ ] Fav Icon / Application icons need to be added in Storybook
- [ ] Check also theme color for mobile status bar color

**Comment by clastzoo** [comment]
@clastzoo send favicons to @nobilo @mladenplaninicic

**Comment by clastzoo** [comment]
cc @nobilo @mladenplaninicic 

[favicon-baloise.zip](https://github.com/baloise-incubator/design-system/files/10153123/favicon-baloise.zip)

**Comment by hirsch88** [comment]
use https://realfavicongenerator.net
