### ISSUE TITLE
wrong dependency versions in design-system-components/package.json to other @baloise libs

### ISSUE THREAD

**Issue by svene** [baloise-incubator/design-system#931]
desing-system-components/package.json V11.0.17 contains the following dependencies:
    "@baloise/design-system-css": "11.0.12",
    "@baloise/design-system-fonts": "11.0.12",
    "@baloise/design-system-icons": "11.0.12",
    "@baloise/design-system-tokens": "11.0.12",

In my opinion this is wrong and they should point to the the same version.

**Comment by hirsch88** [comment]
@svene  fixed with v11.0.18
