### ISSUE TITLE
[iPhone 12 mini][Safari] Popover not centered

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#942]
**Steps to reproduce:** 

1. Open Popover Basic (iPhone, Safari)
2. Click on Trigger

>> Modal dialogue is not centered

![Image](https://user-images.githubusercontent.com/29020214/205647195-e1d9f210-19ae-40e4-9ade-6bd82d2d4d78.jpeg)

**Comment by hirsch88** [comment]
could not reproduced
