### ISSUE TITLE
[iPhone 12 mini][Safari] Tab not visible

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#944]
Steps to reproduce: 

1. Go to Tab Basic (iPhone, Safari)
2. Open component fullscreen

>> First tab not completely visible

![Image](https://user-images.githubusercontent.com/29020214/205648494-d7aa392e-cf9b-478f-b640-661a9ff2244f.jpeg)

**Comment by hirsch88** [comment]
Added to nav refactoring
