### ISSUE TITLE
[iPhone][Chrome, Safari] Issues with table

### ISSUE THREAD

**Issue by Gagne87** [baloise-incubator/design-system#959]
Steps to reproduce: 

**First issue:**
1. Open Table Basic on Chrome (Mobile) 
>> Buttons should not be aligned vertically (I would expect a solution as on desktop -> otherwise accessibility is quite bad

**Second issue:**

1. Open Table Ag Grid on Chrome (Mobile) 
>> Table is not shown correctly 

![Image](https://user-images.githubusercontent.com/29020214/206208964-1a4a59f8-4193-40b0-94a3-4586adbf1585.jpeg)

![Image](https://user-images.githubusercontent.com/29020214/206208997-4d5fd73c-7e50-4745-beee-d19bef49f4e6.jpeg)

**Comment by hirsch88** [comment]
https://github.com/baloise/design-system/issues/702
