### ISSUE TITLE
control inside radio-button-group influences other formcontrol on focus

### ISSUE THREAD

**Issue by m4rc0z** [baloise-incubator/design-system#962]
In our application we have a radio button and inside this one we have other controls. Since version 11.0.11 there was a bug introduced.

If we change the input inside of a radio-button then the value of the radio button also gets updated with the value additionally to the input value itself.

I have provided a branch in the examples app (see branch with name: bug/issue_962)

Also a short screen recording which shows the value of the radio button. Which is first updated with true/false values and later with the value which was typed into the input field (which is wrong).

see:

![radiobutton_invalid_bug](https://user-images.githubusercontent.com/20516386/206236187-5fe68e6b-d1ab-4094-bb0d-cf95489ec0df.gif)

**Comment by hirsch88** [comment]
![Image](https://user-images.githubusercontent.com/6384499/206406228-ee39f12f-efb5-4f79-a69b-a03cff5bb3c8.png)

**Comment by hirsch88** [comment]
@m4rc0z can you please send us the HTML template? I could not reproduce it yet.

**Comment by hirsch88** [comment]
@nobilo & @m4rc0z looks like it is an angular form issue

**Comment by hirsch88** [comment]
https://github.com/baloise-incubator/design-system/pull/971

**Comment by m4rc0z** [comment]
works 👍
