### ISSUE TITLE
[bal-footer] -  Add DE and social links

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#968]
- [x] The footer component should also show the social media links from the CMS API
- [x] The footer should support Germany
- [x] install 3.11.0 web-app-utils

**Comment by hirsch88** [comment]
So far the API is also available for Germany, however the social media links are not yet intergrated

**Comment by hirsch88** [comment]
![Image](https://user-images.githubusercontent.com/6384499/224058204-ee7d42d6-60ef-462d-87d9-75e612d1fe01.png)

**Comment by Gagne87** [comment]
Hi @mladenplaninicic , created the component on Figma (https://www.figma.com/file/lgDn2QZqoJJlYzGTe6cOmr/%F0%9F%A7%A9-Components?node-id=1575%3A626) as discussed yesterday. The component is also published on Figma now and can be used there.
