### ISSUE TITLE
[bal-datepicker] show no valid dates, when selected by years directly

### ISSUE THREAD

**Issue by Sw0rdiX** [baloise-incubator/design-system#975]
## Detailed description

date-picker do not show valid date if u change the year directly

https://baloise-design-system.vercel.app/?path=/story/components-form-datepicker--basic&args=defaultDate:2022-12-14;closeOnSelect:true;max:2023-02-28;value:2022-12-14;min:2022-12-14

![image](https://user-images.githubusercontent.com/3681337/207557779-bc883a13-8590-4b2e-a90b-32e307691e9d.png)

https://user-images.githubusercontent.com/3681337/207558072-a04e00e6-bfad-4f24-b6d9-7039d76f24a4.mp4

**Comment by hirsch88** [comment]
will be done by [#207](https://github.com/baloise-incubator/design-system/issues/207)
