### ISSUE TITLE
first click in bal-select not take over selected value (in combination display invalid bal-field)

### ISSUE THREAD

**Issue by tklueber** [baloise-incubator/design-system#988]
I hope I have explained the following problem well enough (I have also linked an example):

initial situation/environment
In our premium calculator, we have the postcode - city component. If a unique postcode is entered, the respective city appears in a corresponding field.

If there are several cities for a postcode, then a selection (bal-select/bal-select-options) component appears and you can select the desired city. So far so good.

what goes wrong
Unfortunately, the selection only takes over the selection with the second click (at the first try). After that second click, the selection reacts immediately and directly as desired.
![issue_dbl_click](https://user-images.githubusercontent.com/292344/208101688-d6b8ced0-35d0-4427-870e-5864695a1bed.gif)

analysis
We found out that the error is related to the <bal-field [invalid]...> behavior. We evaluate the validity by calling a function and checking if the respective component is touched and invalid. 
The first click switches the component to invalid (and the selected value is not taken over) and with the second click the value is selected and the invalid check passed. 

example app:
https://github.com/baloise/design-system-examples/tree/issue_bal_select_dbl_click 

We want to know:
- Is this a bug?
- Is there a best practice for how to handle invalid status better (we know that function call in html is not optimal)?

**Comment by hirsch88** [comment]
Hi @tklueber to fix it now just use `[]` an empty array as a start value. 

We created a fix for nullable values => https://github.com/baloise-incubator/design-system/pull/993
