### ISSUE TITLE
[bal-button] loading state issue

### ISSUE THREAD

**Issue by madaluca** [baloise-incubator/design-system#998]
if the same form is submitted more then one time in a row, the bal-spinner inside the submit button adds a new svg each time

<img width="1525" alt="Screenshot 2022-12-20 at 14 48 40" src="https://user-images.githubusercontent.com/17945926/208673135-2d7c62bf-194b-45b4-ba81-7eb8413087f9.png">

**Comment by hirsch88** [comment]
linked with [#897](https://github.com/baloise-incubator/design-system/issues/897)

**Comment by madaluca** [comment]
@hirsch88 is this fix already released?
